# -*- makefile -*-

CFLAGS += -Wpedantic -W -Wall -frounding-math

TYPE_UNDER_TEST := double

all:: check_worst

check_worst: check_worst.o $(FUNCTION_UNDER_TEST).o $(FUNCTION_UNDER_TEST)_mpfr.o
	$(CC) -o $@ $^ -lmpfr -lm

%.o: %.c
	$(CC) $(CFLAGS) -I ../support -c -o $@ $<

check_worst.o: ../support/check_worst.c
	$(CC) $(CFLAGS) -I . -c -o $@ $<

clean::
	rm -f *.o check_worst

include ../../generic/support/Makefile.bivariate
