/* Correctly-rounded exp10m1 function for binary64 value.

Copyright (c) 2022-2023 Paul Zimmermann, Tom Hubrecht and Claude-Pierre Jeannerod

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <stdio.h>
#include <stdint.h>
#include <math.h> // needed to define exp10m1() since glibc does not have it

/* __builtin_roundeven was introduced in gcc 10:
   https://gcc.gnu.org/gcc-10/changes.html,
   and in clang 17 */
#if (defined(__GNUC__) && __GNUC__ >= 10) || (defined(__clang__) && __clang_major__ >= 17)
#define HAS_BUILTIN_ROUNDEVEN
#endif

#if !defined(HAS_BUILTIN_ROUNDEVEN) && (defined(__GNUC__) || defined(__clang__)) && (defined(__AVX__) || defined(__SSE4_1__))
inline double __builtin_roundeven(double x){
   double ix;
#if defined __AVX__
   __asm__("vroundsd $0x8,%1,%1,%0":"=x"(ix):"x"(x));
#else /* __SSE4_1__ */
   __asm__("roundsd $0x8,%1,%0":"=x"(ix):"x"(x));
#endif
   return ix;
}
#define HAS_BUILTIN_ROUNDEVEN
#endif

#ifndef HAS_BUILTIN_ROUNDEVEN
#include <math.h>
/* round x to nearest integer, breaking ties to even */
static double
__builtin_roundeven (double x)
{
  double y = round (x); /* nearest, away from 0 */
  if (fabs (y - x) == 0.5)
  {
    /* if y is odd, we should return y-1 if x>0, and y+1 if x<0 */
    union { double f; uint64_t n; } u, v;
    u.f = y;
    v.f = (x > 0) ? y - 1.0 : y + 1.0;
    if (__builtin_ctz (v.n) > __builtin_ctz (u.n))
      y = v.f;
  }
  return y;
}
#endif

/* LN10H+LN10L approximates log(10), with error bounded by 2^-106.3 */
#define LN10H 0x1.26bb1bbb55516p+1
#define LN10L -0x1.f48ad494ea3e9p-53

/****************** code copied from pow.[ch] ********************************/

// Multiply exactly a and b, such that *hi + *lo = a * b.
static inline void a_mul(double *hi, double *lo, double a, double b) {
  *hi = a * b;
  *lo = __builtin_fma (a, b, -*hi);
}

// Multiply a double with a double double : a * (bh + bl)
static inline void s_mul (double *hi, double *lo, double a, double bh,
                          double bl) {
  a_mul (hi, lo, a, bh); /* exact */
  *lo = __builtin_fma (a, bl, *lo);
}

// Returns (ah + al) * (bh + bl) - (al * bl)
static inline void d_mul(double *hi, double *lo, double ah, double al,
                         double bh, double bl) {
  a_mul (hi, lo, ah, bh);
  *lo = __builtin_fma (ah, bl, *lo);
  *lo = __builtin_fma (al, bh, *lo);
}

// Add a + b, assuming |a| >= |b|
static inline void
fast_two_sum(double *hi, double *lo, double a, double b)
{
  double e;

  *hi = a + b;
  e = *hi - a; /* exact */
  *lo = b - e; /* exact */
}

// Add a + (bh + bl), assuming |a| >= |bh|
static inline void fast_sum(double *hi, double *lo, double a, double bh,
                            double bl) {
  fast_two_sum(hi, lo, a, bh);
  /* |(a+bh)-(hi+lo)| <= 2^-105 |hi| and |lo| < ulp(hi) */
  *lo += bl;
  /* |(a+bh+bl)-(hi+lo)| <= 2^-105 |hi| + ulp(lo),
     where |lo| <= ulp(hi) + |bl|. */
}

/* The following is a degree-4 polynomial generated by Sollya for exp(x)
   over [-0.000130273,0.000130273] with absolute error < 2^-74.346. */
static const double Q_1[] = {0x1p0,                 /* degree 0 */
                             0x1p0,                 /* degree 1 */
                             0x1p-1,                /* degree 2 */
                             0x1.5555555995d37p-3,  /* degree 3 */
                             0x1.55555558489dcp-5   /* degree 4 */
};

// Approximation for the fast path of exp(z) for z=zh+zl,
// with |z| < 0.000130273 < 2^-12.88 and |zl| < 2^-42.6
// (assuming x^y does not overflow or underflow)
static inline void q_1 (double *hi, double *lo, double zh, double zl) {
  double z = zh + zl;
  double q = __builtin_fma (Q_1[4], zh, Q_1[3]);

  q = __builtin_fma (q, z, Q_1[2]);

  fast_two_sum (hi, lo, Q_1[1], q * z);

  d_mul (hi, lo, zh, zl, *hi, *lo);

  fast_sum (hi, lo, Q_1[0], *hi, *lo);
}

/* For 0 <= i < 64, T1[i] = (h,l) such that h+l is the best double-double
   approximation of 2^(i/64). The approximation error is bounded as follows:
   |h + l - 2^(i/64)| < 2^-107. */
static const double T1[][2] = {
    {              0x1p+0,                 0x0p+0},
    {0x1.02c9a3e778061p+0, -0x1.19083535b085dp-56},
    {0x1.059b0d3158574p+0,  0x1.d73e2a475b465p-55},
    {0x1.0874518759bc8p+0,  0x1.186be4bb284ffp-57},
    {0x1.0b5586cf9890fp+0,  0x1.8a62e4adc610bp-54},
    {0x1.0e3ec32d3d1a2p+0,  0x1.03a1727c57b53p-59},
    {0x1.11301d0125b51p+0, -0x1.6c51039449b3ap-54},
    { 0x1.1429aaea92dep+0, -0x1.32fbf9af1369ep-54},
    {0x1.172b83c7d517bp+0, -0x1.19041b9d78a76p-55},
    {0x1.1a35beb6fcb75p+0,  0x1.e5b4c7b4968e4p-55},
    {0x1.1d4873168b9aap+0,  0x1.e016e00a2643cp-54},
    {0x1.2063b88628cd6p+0,  0x1.dc775814a8495p-55},
    {0x1.2387a6e756238p+0,  0x1.9b07eb6c70573p-54},
    {0x1.26b4565e27cddp+0,  0x1.2bd339940e9d9p-55},
    {0x1.29e9df51fdee1p+0,  0x1.612e8afad1255p-55},
    {0x1.2d285a6e4030bp+0,  0x1.0024754db41d5p-54},
    {0x1.306fe0a31b715p+0,  0x1.6f46ad23182e4p-55},
    {0x1.33c08b26416ffp+0,  0x1.32721843659a6p-54},
    {0x1.371a7373aa9cbp+0, -0x1.63aeabf42eae2p-54},
    {0x1.3a7db34e59ff7p+0, -0x1.5e436d661f5e3p-56},
    {0x1.3dea64c123422p+0,  0x1.ada0911f09ebcp-55},
    {0x1.4160a21f72e2ap+0, -0x1.ef3691c309278p-58},
    {0x1.44e086061892dp+0,   0x1.89b7a04ef80dp-59},
    { 0x1.486a2b5c13cdp+0,   0x1.3c1a3b69062fp-56},
    {0x1.4bfdad5362a27p+0,  0x1.d4397afec42e2p-56},
    {0x1.4f9b2769d2ca7p+0, -0x1.4b309d25957e3p-54},
    {0x1.5342b569d4f82p+0, -0x1.07abe1db13cadp-55},
    {0x1.56f4736b527dap+0,  0x1.9bb2c011d93adp-54},
    {0x1.5ab07dd485429p+0,  0x1.6324c054647adp-54},
    {0x1.5e76f15ad2148p+0,  0x1.ba6f93080e65ep-54},
    {0x1.6247eb03a5585p+0, -0x1.383c17e40b497p-54},
    {0x1.6623882552225p+0, -0x1.bb60987591c34p-54},
    {0x1.6a09e667f3bcdp+0, -0x1.bdd3413b26456p-54},
    {0x1.6dfb23c651a2fp+0, -0x1.bbe3a683c88abp-57},
    {0x1.71f75e8ec5f74p+0, -0x1.16e4786887a99p-55},
    {0x1.75feb564267c9p+0, -0x1.0245957316dd3p-54},
    {0x1.7a11473eb0187p+0, -0x1.41577ee04992fp-55},
    {0x1.7e2f336cf4e62p+0,  0x1.05d02ba15797ep-56},
    {0x1.82589994cce13p+0, -0x1.d4c1dd41532d8p-54},
    {0x1.868d99b4492edp+0, -0x1.fc6f89bd4f6bap-54},
    {0x1.8ace5422aa0dbp+0,  0x1.6e9f156864b27p-54},
    {0x1.8f1ae99157736p+0,  0x1.5cc13a2e3976cp-55},
    {0x1.93737b0cdc5e5p+0, -0x1.75fc781b57ebcp-57},
    { 0x1.97d829fde4e5p+0, -0x1.d185b7c1b85d1p-54},
    { 0x1.9c49182a3f09p+0,  0x1.c7c46b071f2bep-56},
    {0x1.a0c667b5de565p+0, -0x1.359495d1cd533p-54},
    {0x1.a5503b23e255dp+0, -0x1.d2f6edb8d41e1p-54},
    {0x1.a9e6b5579fdbfp+0,  0x1.0fac90ef7fd31p-54},
    {0x1.ae89f995ad3adp+0,  0x1.7a1cd345dcc81p-54},
    {0x1.b33a2b84f15fbp+0, -0x1.2805e3084d708p-57},
    {0x1.b7f76f2fb5e47p+0, -0x1.5584f7e54ac3bp-56},
    {0x1.bcc1e904bc1d2p+0,  0x1.23dd07a2d9e84p-55},
    {0x1.c199bdd85529cp+0,  0x1.11065895048ddp-55},
    {0x1.c67f12e57d14bp+0,  0x1.2884dff483cadp-54},
    {0x1.cb720dcef9069p+0,  0x1.503cbd1e949dbp-56},
    {0x1.d072d4a07897cp+0, -0x1.cbc3743797a9cp-54},
    {0x1.d5818dcfba487p+0,  0x1.2ed02d75b3707p-55},
    {0x1.da9e603db3285p+0,  0x1.c2300696db532p-54},
    {0x1.dfc97337b9b5fp+0, -0x1.1a5cd4f184b5cp-54},
    {0x1.e502ee78b3ff6p+0,  0x1.39e8980a9cc8fp-55},
    {0x1.ea4afa2a490dap+0, -0x1.e9c23179c2893p-54},
    {0x1.efa1bee615a27p+0,   0x1.dc7f486a4b6bp-54},
    { 0x1.f50765b6e454p+0,  0x1.9d3e12dd8a18bp-54},
    {0x1.fa7c1819e90d8p+0,  0x1.74853f3a5931ep-55},
};

/* For 0 <= i < 64, T2[i] = (h,l) such that h+l is the best double-double
   approximation of 2^(i/2^12). The approximation error is bounded as follows:
   |h + l - 2^(i/2^12)| < 2^-107. */
static const double T2[][2] = {
    {              0x1p+0,                 0x0p+0},
    {0x1.000b175effdc7p+0,  0x1.ae8e38c59c72ap-54},
    {0x1.00162f3904052p+0, -0x1.7b5d0d58ea8f4p-58},
    {0x1.0021478e11ce6p+0,  0x1.4115cb6b16a8ep-54},
    {0x1.002c605e2e8cfp+0, -0x1.d7c96f201bb2fp-55},
    {0x1.003779a95f959p+0,  0x1.84711d4c35e9fp-54},
    {0x1.0042936faa3d8p+0, -0x1.0484245243777p-55},
    { 0x1.004dadb113dap+0, -0x1.4b237da2025f9p-54},
    {0x1.0058c86da1c0ap+0, -0x1.5e00e62d6b30dp-56},
    {0x1.0063e3a559473p+0,  0x1.a1d6cedbb9481p-54},
    {0x1.006eff583fc3dp+0, -0x1.4acf197a00142p-54},
    {0x1.007a1b865a8cap+0, -0x1.eaf2ea42391a5p-57},
    {0x1.0085382faef83p+0,  0x1.da93f90835f75p-56},
    {0x1.00905554425d4p+0, -0x1.6a79084ab093cp-55},
    {0x1.009b72f41a12bp+0,  0x1.86364f8fbe8f8p-54},
    {0x1.00a6910f3b6fdp+0, -0x1.82e8e14e3110ep-55},
    {0x1.00b1afa5abcbfp+0, -0x1.4f6b2a7609f71p-55},
    {0x1.00bcceb7707ecp+0, -0x1.e1a258ea8f71bp-56},
    {0x1.00c7ee448ee02p+0,  0x1.4362ca5bc26f1p-56},
    {0x1.00d30e4d0c483p+0,  0x1.095a56c919d02p-54},
    {0x1.00de2ed0ee0f5p+0, -0x1.406ac4e81a645p-57},
    { 0x1.00e94fd0398ep+0,  0x1.b5a6902767e09p-54},
    {0x1.00f4714af41d3p+0, -0x1.91b2060859321p-54},
    {0x1.00ff93412315cp+0,  0x1.427068ab22306p-55},
    {0x1.010ab5b2cbd11p+0,  0x1.c1d0660524e08p-54},
    {0x1.0115d89ff3a8bp+0, -0x1.e7bdfb3204be8p-54},
    {0x1.0120fc089ff63p+0,  0x1.843aa8b9cbbc6p-55},
    {0x1.012c1fecd613bp+0, -0x1.34104ee7edae9p-56},
    {0x1.0137444c9b5b5p+0, -0x1.2b6aeb6176892p-56},
    {0x1.01426927f5278p+0,  0x1.a8cd33b8a1bb3p-56},
    {0x1.014d8e7ee8d2fp+0,  0x1.2edc08e5da99ap-56},
    {0x1.0158b4517bb88p+0,  0x1.57ba2dc7e0c73p-55},
    {0x1.0163da9fb3335p+0,  0x1.b61299ab8cdb7p-54},
    {0x1.016f0169949edp+0, -0x1.90565902c5f44p-54},
    {0x1.017a28af25567p+0,  0x1.70fc41c5c2d53p-55},
    {0x1.018550706ab62p+0,  0x1.4b9a6e145d76cp-54},
    {0x1.019078ad6a19fp+0, -0x1.008eff5142bf9p-56},
    {0x1.019ba16628de2p+0, -0x1.77669f033c7dep-54},
    {0x1.01a6ca9aac5f3p+0, -0x1.09bb78eeead0ap-54},
    {0x1.01b1f44af9f9ep+0,  0x1.371231477ece5p-54},
    {0x1.01bd1e77170b4p+0,  0x1.5e7626621eb5bp-56},
    {0x1.01c8491f08f08p+0, -0x1.bc72b100828a5p-54},
    { 0x1.01d37442d507p+0, -0x1.ce39cbbab8bbep-57},
    {0x1.01de9fe280ac8p+0,  0x1.16996709da2e2p-55},
    {0x1.01e9cbfe113efp+0, -0x1.c11f5239bf535p-55},
    {0x1.01f4f8958c1c6p+0,  0x1.e1d4eb5edc6b3p-55},
    {0x1.020025a8f6a35p+0, -0x1.afb99946ee3fp-54},
    {0x1.020b533856324p+0, -0x1.8f06d8a148a32p-54},
    {0x1.02168143b0281p+0, -0x1.2bf310fc54eb6p-55},
    {0x1.0221afcb09e3ep+0, -0x1.c95a035eb4175p-54},
    {0x1.022cdece68c4fp+0, -0x1.491793e46834dp-54},
    {0x1.02380e4dd22adp+0, -0x1.3e8d0d9c49091p-56},
    {0x1.02433e494b755p+0, -0x1.314aa16278aa3p-54},
    {0x1.024e6ec0da046p+0,  0x1.48daf888e9651p-55},
    {0x1.02599fb483385p+0,  0x1.56dc8046821f4p-55},
    {0x1.0264d1244c719p+0,  0x1.45b42356b9d47p-54},
    {0x1.027003103b10ep+0, -0x1.082ef51b61d7ep-56},
    {0x1.027b357854772p+0,  0x1.2106ed0920a34p-56},
    {0x1.0286685c9e059p+0, -0x1.fd4cf26ea5d0fp-54},
    {0x1.02919bbd1d1d8p+0, -0x1.09f8775e78084p-54},
    {0x1.029ccf99d720ap+0,  0x1.64cbba902ca27p-58},
    {0x1.02a803f2d170dp+0,  0x1.4383ef231d207p-54},
    {0x1.02b338c811703p+0,  0x1.4a47a505b3a47p-54},
    {0x1.02be6e199c811p+0,  0x1.e47120223467fp-54},
};

typedef union {
  double f;
  uint64_t u;
} f64_u;

/*
  Approximation of exp(x), where x = xh + xl

  exp(x) is approximated by hi + lo.

  For the error analysis, we only consider the case where x^y does not
  overflow or underflow. We get:

  (hi + lo) / exp(xh + xl) = 1 + eps with |eps| < 2^-74.139

  Assumes |xl/xh| < 2^-23.89 and |xl| < 2^-14.3486.

  See analysis before the exp_1() call in cr_pow(), which proves
  |rl| < 2^-23.89 |rh| (here xh=rh and xl=rl).

  At output, we also have 0.99985 < hi+lo < 1.99995 and |lo/hi| < 2^-41.4.
*/

static inline void exp_1 (double *hi, double *lo, double xh, double xl) {
  int bug = xh == 0x1.62e42d29db3f1p+9;
#define INVLOG2 0x1.71547652b82fep+12 /* |INVLOG2-2^12/log(2)| < 2^-43.4 */
  double k = __builtin_roundeven (xh * INVLOG2);
  if (bug) printf ("k=%la\n", k);

  double kh, kl;
#define LOG2H 0x1.62e42fefa39efp-13
#define LOG2L 0x1.abc9e3b39803fp-68
  s_mul (&kh, &kl, k, LOG2H, LOG2L);

  double yh, yl;
  fast_two_sum (&yh, &yl, xh - kh, xl);
  yl -= kl;

  int64_t K = k; /* Note: k is an integer, this is just a conversion. */
  int64_t M = (K >> 12) + 0x3ff;
  int64_t i2 = (K >> 6) & 0x3f;
  int64_t i1 = K & 0x3f;

  double t1h = T1[i2][0], t1l = T1[i2][1], t2h = T2[i1][0], t2l = T2[i1][1];
  d_mul (hi, lo, t2h, t2l, t1h, t1l);

  double qh, ql;
  q_1 (&qh, &ql, yh, yl);

  d_mul (hi, lo, *hi, *lo, qh, ql);

  /* Scale by 2^k. Warning: for x near 1024, we can have k=2^22, thus
     M = 2047, which encodes Inf */
  f64_u _d;
  _d.u = M << 52;
  if (__builtin_expect (M == 0x7ff, 0))
  {
    *hi *= 2.0;
    *lo *= 2.0;
    _d.u = (M-1) << 52;
  }
  *hi *= _d.f;
  *lo *= _d.f;
}

/****************** end of code copied from pow.[ch] *************************/

/****************** code copied from expm1.c *********************************/

/* The following is a degree-7 polynomial generated by Sollya for exp(z)
   over [-0.000130273,0.000130273] with absolute error < 2^-113.218
   (see file exp_accurate.sollya). Since we use this code only for
   |x| > 0.0625 in exp10m1(x), the corresponding relative error for exp10m1
   is about 2^-113.218/|exp10m1(-0.0625)| which is about 2^-110. */
static const double Q_2[] = {
  0x1p0, // degree 0, Q_2[0]
  0x1p0, // degree 1, Q_2[1]
  0x1p-1, // degree 2, Q_2[2]
  0x1.5555555555555p-3, 0x1.55555555c4d26p-57, // degree 3, Q_2[3], Q_2[4]
  0x1.5555555555555p-5, // degree 4, Q_2[5]
  0x1.1111111111111p-7, // degree 5, Q_2[6]
  0x1.6c16c3fbb4213p-10, // degree 6, Q_2[7]
  0x1.a01a023ede0d7p-13, // degree 7, Q_2[8]
};

// Approximation for the accurate path of exp(z) for z=zh+zl,
// with |z| < 0.000130273 < 2^-12.88 and |zl| < 2^-42.6
// (assuming x^y does not overflow or underflow)
static inline void q_2 (double *hi, double *lo, double zh, double zl) {
  /* Let q[0]..q[7] be the coefficients of degree 0..7 of Q_2.
     The ulp of q[7]*z^7 is at most 2^-155, thus we can compute q[7]*z^7
     in double precision only.
     The ulp of q[6]*z^6 is at most 2^-139, thus we can compute q[6]*z^6
     in double precision only.
     The ulp of q[5]*z^5 is at most 2^-124, thus we can compute q[5]*z^5
     in double precision only. */
  double z = zh + zl;
  double q = __builtin_fma (Q_2[8], zh, Q_2[7]);

  q = __builtin_fma (q, z, Q_2[6]);

  q = __builtin_fma (q, z, Q_2[5]);

  // multiply q by z and add Q_2[3] + Q_2[4]
  a_mul (hi, lo, q, z);
  double t;
  fast_two_sum (hi, &t, Q_2[3], *hi);
  *lo += t + Q_2[4];

  // multiply hi+lo by zh+zl and add Q_2[2]
  d_mul (hi, lo, *hi, *lo, zh, zl);
  fast_two_sum (hi, &t, Q_2[2], *hi);
  *lo += t;

  // multiply hi+lo by zh+zl and add Q_2[1]
  d_mul (hi, lo, *hi, *lo, zh, zl);
  fast_two_sum (hi, &t, Q_2[1], *hi);
  *lo += t;

  // multiply hi+lo by zh+zl and add Q_2[0]
  d_mul (hi, lo, *hi, *lo, zh, zl);
  fast_two_sum (hi, &t, Q_2[0], *hi);
  *lo += t;
}

// returns a double-double approximation hi+lo of exp(x*log(10))
// assumes -0x1.041704c068efp+4 < x <= 0x1.34413509f79fep+8
static inline void exp_2 (double *hi, double *lo, double x) {

  double eh, el;
#define INVLOG2_10 0x1.a934f0979a371p+13 // 2^12*log(10)/log(2)
  double k = __builtin_roundeven (x * INVLOG2_10); // -221184 <= k <= 4194304
  if (__builtin_expect (k == 4194304, 0))
    k = 4194303; // ensures M < 2047 below

  double yh, yl;
  /* LOG2H+LOG2_10M+LOG2L approximates log(2)/log(10)/2^12, with LOG2_10M
     representable on 30 bits so that LOG2_10M*k is exact */
#define LOG2_10H 0x1.34413509f79ffp-14
#define LOG2_10M -0x1.9dc1da98p-71
#define LOG2_10L -0x1.4fd20dba1f655p-103
  yh = __builtin_fma (-k, LOG2_10H, x); // exact
  fast_two_sum (&yh, &yl, yh, -k * LOG2_10M);
  yl = __builtin_fma (-k, LOG2_10L, yl);
  // now multiply yh+yl by log(10)
  s_mul (&eh, &el, yh, LN10H, LN10L);
  yh = eh;
  yl = __builtin_fma (yl, LN10H, el);

  int64_t K = k;
  int64_t M = (K >> 12) + 0x3ff;
  int64_t i2 = (K >> 6) & 0x3f;
  int64_t i1 = K & 0x3f;

  double t1h = T1[i2][0], t1l = T1[i2][1], t2h = T2[i1][0], t2l = T2[i1][1];
  d_mul (hi, lo, t2h, t2l, t1h, t1l);

  double qh, ql;
  q_2 (&qh, &ql, yh, yl);

  d_mul (hi, lo, *hi, *lo, qh, ql);
  f64_u _d;

  _d.u = M << 52;
  if (__builtin_expect (M == 0x7ff, 0))
  {
    *hi *= 2.0;
    *lo *= 2.0;
    _d.u = (M-1) << 52;
  }
  *hi *= _d.f;
  *lo *= _d.f;
}

/****************** end of code copied from expm1.c **************************/

typedef union {double f; uint64_t u;} b64u64_u;

/* The following is a degree-11 polynomial generated by Sollya
   (file exp10m1_fast.sollya),
   which approximates exp10m1(x) with relative error bounded by 2^-69.58
   for |x| <= 0.0625. */
static const double P[] = {
  0x1.26bb1bbb55516p+1, -0x1.f48abcf79e094p-53, // degree 1, P[0], P[1]
  0x1.53524c73cea69p+1, -0x1.e1badf796d704p-53, // degree 2, P[2], P[3]
  0x1.0470591de2ca4p+1, 0x1.7db8caacb2ceap-53,  // degree 3, P[4], P[5]
  0x1.2bd7609fd98bap0,   // degree 4, P[6]
  0x1.1429ffd1d4d98p-1,  // degree 5, P[7]
  0x1.a7ed7084998e1p-3,  // degree 6, P[8]
  0x1.16e4dfc30944bp-4,  // degree 7, P[9]
  0x1.4116ae4b57526p-6,  // degree 8, P[10]
  0x1.4897c6a90f61cp-8,  // degree 9, P[11]
  0x1.2ec689c32b3ap-10,  // degree 10, P[12]
  0x1.faced20d698fep-13, // degree 11. P[13]
};

/* |x| <= 0.0625, put in h + l a double-double approximation of exp10m1(x),
   and return the maximal corresponding absolute error.
   We also have |x| > 0x1.3a7679bab5437p-54.
   With xmin=RR("0x1.3a7679bab5437p-54",16), the routine
   exp10m1_fast_tiny_all(xmin,0.0625,2^-68.08) in exp10m1.sage returns
   3.19954871401135e-21 < 2^-68.08, and
   exp10m1_fast_tiny_all(-0.0625,-xmin,2^-67.95) returns
   3.50730205778814e-21 < 2^-67.95, which proves the relative
   error is bounded by 2^-67.95. */
static double
exp10m1_fast_tiny (double *h, double *l, double x)
{
  /* The maximal value of |c5*x^5/exp10m1(x)| over [-0.0625,0.0625]
     (where c5 is the degree-5 coefficient) is less than 2^-17.991,
     thus we can compute the coefficients of degree 5 or higher using
     double precision only. */
  double x2 = x * x, x4 = x2 * x2;
  double c9 = __builtin_fma (P[12], x, P[11]); // degree 9
  double c7 = __builtin_fma (P[10], x, P[9]);  // degree 7
  double c5 = __builtin_fma (P[8], x, P[7]);   // degree 5
  c9 = __builtin_fma (P[13], x2, c9);          // degree 9
  c5 = __builtin_fma (c7, x2, c5);             // degree 5
  c5 = __builtin_fma (c9, x4, c5);             // degree 5
  double t;
  // multiply c5 by x and add P[6] (degree 4)
  a_mul (h, l, c5, x);
  fast_two_sum (h, &t, P[6], *h);
  *l += t;
  // multiply (h,l) by x and add P[4]+P[5] (degree 3)
  s_mul (h, l, x, *h, *l);
  fast_two_sum (h, &t, P[4], *h);
  *l += t + P[5];
  // multiply (h,l) by x and add P[2]+P[3] (degree 2)
  s_mul (h, l, x, *h, *l);
  fast_two_sum (h, &t, P[2], *h);
  *l += t + P[3];
  // multiply (h,l) by x and add P[0]+P[1] (degree 1)
  s_mul (h, l, x, *h, *l);
  fast_two_sum (h, &t, P[0], *h);
  *l += t + P[1];
  // multiply (h,l) by x
  s_mul (h, l, x, *h, *l);
  return 0x1.0ap-68 * *h; // 2^-67.95 < 0x1.0ap-68
}

/* Given -0x1.041704c068efp+4 < x < 0x1.3a7679bab5437p-54 or
   0x1.3a7679bab5437p-54 < x <= 0x1.34413509f79fep+8, put in h + l a
   double-double approximation of exp10m1(x), and return the maximal
   corresponding absolute error.
   The input tiny is true iff |x| <= 0.0625. */
static double
exp10m1_fast (double *h, double *l, double x, int tiny)
{
  if (tiny) // |x| <= 0.125
    return exp10m1_fast_tiny (h, l, x);

  /* now -0x1.041704c068efp+4 < x < -0.0625 or
     0.0625 < x <= 0x1.34413509f79fep+8: we approximate exp(x*log(10))
     and subtract 1 */
  s_mul (h, l, x, LN10H, LN10L);
  /* s_mul (h, l, x, LN10H, LN10L) decomposes into:
     a_mul (h, t, x, LN10H)
     l += fma (x, LN10L, t)
     The a_mul() call is exact, and the error of the fma() is bounded by
     ulp(l).
     We have |t| <= ulp(h) <= ulp(LN10H*0x1.34413509f79fep+8) = 2^-43,
     |t+x*LN10L| <= 2^-43 * 0x1.34413509f79fep+8*|LN10L| < 2^-42.3,
     thus |l| <= |t| + |x*LN10L| + ulp(t+x*LN10L)
              <= 2^-42.3 + 2^-95 <= 2^-42.2, and ulp(l) <= 2^-95.
     Thus:
     |h+l - x*log(10)| <= |h+l - x*(LN10H+LN10L)| + |x|*|LN10H+LN10L-log(10)|
                        <= 2^-95 + 0x1.34413509f79fep+8*2^-106.3 < 2^-94.8 */
  exp_1 (h, l, *h, *l);
  /* h_out + l_out = exp(h + l) * (1 + eps) with |eps| < 2^-74.139
                   = exp(x*log(10) + eps0) * (1 + eps)
                   with |eps0| < 2^-94.8 and |eps| < 2^-74.139
                   = 10^x * (1 + eps1) with |eps1| < 2^-74.138 */
  double u;
  if (x >= 0) // implies h >= 1 and the fast_two_sum pre-condition holds
    fast_two_sum (h, &u, *h, -1.0);
  else
    fast_two_sum (h, &u, -1.0, *h); // x < 0 thus h <= 1
  *l += u;
  /* The error in the above fast_two_sum is bounded by 2^-105*|h|,
     with the new value of h, thus the total absolute error is bounded
     by eps1*|h_in|+2^-105*|h|.
     Relatively to h this yields eps1*|h_in/h| + 2^-105, where the maximum
     of |h_in/h| is obtained for x near -0.0625, with |10^x/(10^x-1)| < 6.47.
     We get a relative error bound of 2^-74.138*6.47 + 2^-105 < 2^-71.44. */
  return 0x1.7ap-72 * *h; /* 2^-71.44 < 0x1.7ap-72 */
}

/* The following is a degree-17 polynomial generated by Sollya
   (file exp10m1_accurate.sollya),
   which approximates exp10m1(x) with relative error bounded by 2^-107.506
   for |x| <= 0.0625. */
static const double Q[] = {
  0x1.26bb1bbb55516p+1, -0x1.f48ad494ea3e9p-53,  // degree 1: Q[0], Q[1]
  0x1.53524c73cea69p+1, -0x1.e2bfab318d696p-53,  // degree 2: Q[2], Q[3]
  0x1.0470591de2ca4p+1, 0x1.823527cebf918p-53,   // degree 3: Q[4], Q[5]
  0x1.2bd7609fd98c4p+0, 0x1.31ea51f6641dfp-54,   // degree 4: Q[6], Q[7]
  0x1.1429ffd1d4d76p-1, 0x1.117195be7f232p-56,   // degree 5: Q[8], Q[9]
  0x1.a7ed70847c8b6p-3, -0x1.4260c5e23d0c8p-58,  // degree 6: Q[10], Q[11]
  0x1.16e4dfc333a87p-4, -0x1.33fd284110905p-58,  // degree 7: Q[12], Q[13]
  0x1.4116b05fdaa5dp-6, -0x1.0721de44d79a8p-61,  // degree 8: Q[14], Q[15]
  0x1.4897c45d93d43p-8,                          // degree 9: Q[16]
  0x1.2ea52b2d182acp-10,                         // degree 10: Q[17]
  0x1.facfd5d905b22p-13,                         // degree 11: Q[18]
  0x1.84fe12df8bde3p-15,                         // degree 12: Q[19]
  0x1.1398ad75d01bfp-17,                         // degree 13: Q[20]
  0x1.6a9e96fbf6be7p-20,                         // degree 14: Q[21]
  0x1.bd456a29007c2p-23,                         // degree 15: Q[22]
  0x1.006cf8378cf9bp-25,                         // degree 16: Q[23]
  0x1.68862b132b6e2p-28,                         // degree 17: Q[24]
};

/* Accurate path for 0x1.3a7679bab5437p-54 < |x| <= 0.0625. */
static double
exp10m1_accurate_tiny (double x)
{
  /* The following exceptional cases have at least 51 identical bits after
     the round bit, thus are hard to correctly round with double-double
     arithmetic. They should be sorted by increasing values of the first
     entry (x). */
#define EXCEPTIONS 1
  static const double exceptions[EXCEPTIONS][3] = {
    {0,0,0},
  };
  int a, b, c;
  for (a = 0, b = EXCEPTIONS; a + 1 != b;)
  {
    /* Invariant: if x is an exceptional case, we have
       exceptions[a][0] <= x and (x < exceptions[b][0] or b = EXCEPTIONS) */
    c = (a + b) / 2;
    if (exceptions[c][0] <= x)
      a = c;
    else
      b = c;
  }
  if (x == exceptions[a][0])
    return exceptions[a][1] + exceptions[a][2];
#undef EXCEPTIONS

  double h, l, t;
  double x2 = x * x, x4 = x2 * x2;
  double c15 = __builtin_fma (Q[23], x, Q[22]); // degree 15
  double c13 = __builtin_fma (Q[21], x, Q[20]); // degree 13
  c15 = __builtin_fma (Q[24], x2, c15);         // degree 15
  // add Q[19]*x+c13*x2+c15*x4 to Q[18] (degree 11)
  fast_two_sum (&h, &l, Q[18], Q[19] * x + c13 * x2 + c15 * x4);
  // multiply h+l by x and add Q[17] (degree 10)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[17], h);
  l += t;
  // multiply h+l by x and add Q[16] (degree 9)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[16], h);
  l += t;
  // multiply h+l by x and add Q[14]+Q[15] (degree 8)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[14], h);
  l += t + Q[15];
  // multiply h+l by x and add Q[12]+Q[13] (degree 7)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[12], h);
  l += t + Q[13];
  // multiply h+l by x and add Q[10]+Q[11] (degree 6)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[10], h);
  l += t + Q[11];
  // multiply h+l by x and add Q[8]+Q[9] (degree 5)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[8], h);
  l += t + Q[9];
  // multiply h+l by x and add Q[6]+Q[7] (degree 4)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[6], h);
  l += t + Q[7];
  // multiply h+l by x and add Q[4]+Q[5] (degree 3)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[4], h);
  l += t + Q[5];
  // multiply h+l by x and add Q[2]+Q[3] (degree 2)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[2], h);
  l += t + Q[3];
  // multiply h+l by x and add Q[0]+Q[1] (degree 2)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[0], h);
  l += t + Q[1];
  // multiply h+l by x
  s_mul (&h, &l, x, h, l);
  return h + l;
}

/* assume -0x1.041704c068efp+4 < x < 0x1.3a7679bab5437p-54
   or 0x1.3a7679bab5437p-54 < x <= 0x1.34413509f79fep+8 */
static double exp10m1_accurate (double x)
{
  b64u64_u t = {.f = x};
  uint64_t ux = t.u, ax = ux & 0x7ffffffffffffffflu;

  if (ax <= 0x3fb0000000000000lu) // |x| <= 0.0625
    return exp10m1_accurate_tiny (x);

  /* now -0x1.041704c068efp+4 < x < -0.0625 or
     0.0625 < x <= 0x1.34413509f79fep+8: we approximate exp(x*log(10))
     and subtract 1 */

#define EXCEPTIONS 16
  /* The following table should be sorted by increasing values of the first
     entry (x). */
  static const double exceptions[EXCEPTIONS][3] = {
    {-0x1.f80af51f49489p-3, -0x1.bafcdba0cdf8dp-2, -0x1.ca26eb05ddc4p-107},
    {-0x1.7c356ac2648c6p-3, -0x1.6431514cfe053p-2, 0x1.b7d9e1a5ca32ep-105},
    {-0x1.3a4390b7f0e6fp-3, -0x1.30cc55faf8361p-2, 0x1.9e380aabe2b31p-104},
    {-0x1.e01610b3c2533p-4, -0x1.e46a51c73c432p-3, -0x1.4fd2614c5916bp-105},
    {0x1.561b9bb7ad057p-4, 0x1.b24a081d6bba4p-3, -0x1.0f8432de18ce9p-106},
    {0x1.d63ff6db3698p-4, 0x1.35d9a558ce0c2p-2, 0x1.ad7113ba10482p-106},
    {0x1.12e02aa997af2p-2, 0x1.b5f494d0d82ffp-1, -0x1.469dba5dae6a3p-106},
    {0x1.897b402763181p-2, 0x1.6c274b11a4991p+0, 0x1.c84729725389dp-105},
    {0x1.9a7f5bd8f6bd8p-2, 0x1.84578bd34a91dp+0, -0x1.012e7fffa8537p-104},
    {0x1.aa6e0810a7c29p-2, 0x1.9bd82e7aa167dp+0, -0x1.cff14b231bf42p-111},
    {0x1.522c9f19cc202p-1, 0x1.c9be0d3d8d8f5p+1, 0x1.4460504197e99p-106},
    {0x1p+0,0x1.2p+3,0},
    {0x1p+2, 0x1.3878p+13, 0x0p+0},
    {0x1.2d5494eb1dd13p+2, 0x1.8f169a48a6a87p+15, -0x1.fffffffffffffp-39},
    {0x1.58c1635f834d6p+7, 0x1.8b2dcb245522fp+572, 0x1.fffffffffffffp518},
    {0x1.cde37694f4d1p+7, 0x1.2210fd5a164b7p+767, -0x1.fffffffffffffp+713},
  };
  int a, b, c;
  for (a = 0, b = EXCEPTIONS; a + 1 != b;)
  {
    /* Invariant: if x is an exceptional case, we have
       exceptions[a][0] <= x and (x < exceptions[b][0] or b = EXCEPTIONS) */
    c = (a + b) / 2;
    if (exceptions[c][0] <= x)
      a = c;
    else
      b = c;
  }
  if (x == exceptions[a][0])
    return exceptions[a][1] + exceptions[a][2];
#undef EXCEPTIONS

  double h, l;
  exp_2 (&h, &l, x);
  double u;
  if (x >= 0) // implies h >= 1 and the fast_two_sum pre-condition holds
    fast_two_sum (&h, &u, h, -1.0);
  else
    fast_two_sum (&h, &u, -1.0, h); // x < 0 thus h <= 1
  l += u;
  /* the error in the above fast_two_sum is bounded by 2^-105*|h|,
     with the new value of h */
  return h + l;
}

double
cr_exp10m1 (double x)
{
  b64u64_u t = {.f = x};
  uint64_t ux = t.u, ax = ux & 0x7ffffffffffffffflu;

  if (__builtin_expect (ux >= 0xc03041704c068ef0lu, 0))
  {
    // x = -NaN or x <= -0x1.041704c068efp+4
    if ((ux >> 52) == 0xfff) // -NaN or -Inf
      return (ux > 0xfff0000000000000lu) ? x : -1.0;
    // for x <= -0x1.041704c068efp+4, exp10m1(x) rounds to -1 to nearest
    return -1.0 + 0x1p-54;
  }
  else if (__builtin_expect (ax > 0x40734413509f79felu, 0))
  {
    // x = +NaN or x > 0x1.34413509f79fep+8
    if ((ux >> 52) == 0x7ff) // +NaN
      return x;
    // for x > 0x1.34413509f79fep+8, exp10m1(x) rounds to +Inf to nearest
    return 0x1.fffffffffffffp+1023 * x;
  }
  else if (ax <= 0x3c93a7679bab5437lu) // |x| <= 0x1.3a7679bab5437p-54
    /* then the second term of the Taylor expansion of 10^x-1 at x=0 is
       smaller in absolute value than 1/2 ulp(first term):
       log(10)*x + log(10)^2*x^2/2 + ... */
  {
    double h, l;
    /* we use special code when log(10)*|x| is very small, in which case
       the double-double approximation h+l has its lower part l
       "truncated" */
    if (ax <= 0x3970000000000000lu) // |x| <= 2^-104
    {
      // special case for 0
      if (x == 0)
        return x;
      // scale x by 2^53
      x = x * 0x1p53;
      a_mul (&h, &l, LN10H, x);
      l = __builtin_fma (LN10L, x, l);
      double h2 = h + l; // round to 53-bit precision
      // scale back, hoping to avoid double rounding
      h2 = h2 * 0x1p-53;
      // now subtract back h2 * 2^53 from h to get the correction term
      h = __builtin_fma (-h2, 0x1p53, h);
      // add l
      h += l;
      // add h2 + h * 2^-53
      return __builtin_fma (h, 0x1p-53, h2);
    }
    else // 2^-104 < |x| <= 0x1.3a7679bab5437p-54
    {
      /* The following exceptional cases have at least XXX identical bits after
         the round bit, thus are hard to correctly round with double-double
         arithmetic. They should be sorted by increasing values of the first
         entry (x). */
#define EXCEPTIONS 1
      static const double exceptions[EXCEPTIONS][3] = {
        {0,0,0},
      };
   int a, b, c;
   for (a = 0, b = EXCEPTIONS; a + 1 != b;)
   {
     /* Invariant: if x is an exceptional case, we have
        exceptions[a][0] <= x and (x < exceptions[b][0] or b = EXCEPTIONS) */
     c = (a + b) / 2;
     if (exceptions[c][0] <= x)
       a = c;
     else
       b = c;
   }
  if (x == exceptions[a][0])
    return exceptions[a][1] + exceptions[a][2];
#undef EXCEPTIONS
      /* the 2nd term of the Taylor expansion of 10^x-1 at x=0 is
         log(10)^2/2*x^2 */
      static const double C2 = 0x1.53524c73cea69p+1; // log(10)^2/2
      a_mul (&h, &l, LN10H, x);
      l = __builtin_fma (LN10L, x, l);
      /* h+l approximates the first term x*log(2) */
      /* we add C2*x^2 last, so that in case there is a cancellation in
         LN10L*x+l, it will contribute more bits */
      l += C2 * x * x;
      return h + l;
    }
  }

  /* now -0x1.041704c068efp+4 < x < 0x1.3a7679bab5437p-54
     or 0x1.3a7679bab5437p-54 < x <= 0x1.34413509f79fep+8 */

  double err, h, l;
  err = exp10m1_fast (&h, &l, x, ax <= 0x3fb0000000000000lu);
  double left = h + (l - err);
  double right = h + (l + err);
  if (left == right)
    return left;

  return exp10m1_accurate (x);
}

// fake function as long as GNU libc does not provide it
double exp10m1 (double x)
{
  // we don't use exp10 since it is not in C99 (would need _GNU_SOURCE)
  return pow (10.0, x) - 1.0;
}
