/* Correctly-rounded expm1 function for binary64 value.

Copyright (c) 2022-2023 Paul Zimmermann and Tom Hubrecht

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// FIXME: remove skipped in check_worst_uni.c

#define TRACE 0

#include <stdio.h>
#include <stdint.h>

typedef union {double f; uint64_t u;} b64u64_u;

/* The following is a degree-11 polynomial generated by Sollya
   (file expm1_fast.sollya),
   which approximates expm1(x) with relative error bounded by 2^-67.183
   for |x| <= 0.125. */
static const double P[] = {
  0x0,                   // degree 0 (unused)
  0x1p0,                 // degree 1
  0x1p-1,                // degree 2
  0x1.5555555555555p-3,  // degree 3
  0x1.5555555555553p-5,  // degree 4
  0x1.1111111111bbcp-7,  // degree 5
  0x1.6c16c16c1f8a2p-10, // degree 6
  0x1.a01a0183a908bp-13, // degree 7
  0x1.a01a00383b80dp-16, // degree 8
  0x1.71e02a5f3b87p-19,  // degree 9
  0x1.27fcd07571d4ep-22, // degree 10
  0x1.969ce6c7ee119p-26, // degree 11
};

// Multiply exactly a and b, such that *hi + *lo = a * b. 
static inline void a_mul(double *hi, double *lo, double a, double b) {
  *hi = a * b;
  *lo = __builtin_fma (a, b, -*hi);
}

static inline void
fast_two_sum(double *hi, double *lo, double a, double b)
{
  double e;

  *hi = a + b;
  e = *hi - a; /* exact */
  *lo = b - e; /* exact */
}

/* |x| <= 0.125, put in h + l a double-double approximation of expm1(x),
   and return the maximal corresponding relative error.
   We also have |x| > 0x1.6a09e667f3bccp-53.
   With xmin=RR("0x1.6a09e667f3bccp-53",16), the routine
   expm1_fast_tiny_all(xmin,0.125,2^-64.29) in expm1.sage returns
   4.43378275371923e-20 < 2^-64.29, and
   expm1_fast_tiny_all(-0.125,-xmin,2^-64.13) returns
   4.94311016020191e-20 < 2^-64.13, which proves the relative
   error is bounded by 2^-64.13. */
static double
expm1_fast_tiny (double *h, double *l, double x)
{
  /* The maximal value of |P_fast_tiny[4]*x^4/expm1(x)| over [-0.125,0.125]
     is less than 2^-13.495, thus we can compute the coefficients of degree
     4 or higher using double precision only. */
  double x2 = x * x, x4 = x2 * x2;
  double c10 = __builtin_fma (P[11], x, P[10]);
  double c8 = __builtin_fma (P[9], x, P[8]);
  double c6 = __builtin_fma (P[7], x, P[6]);
  double c4 = __builtin_fma (P[5], x, P[4]);
  c8 = __builtin_fma (c10, x2, c8);
  c4 = __builtin_fma (c6, x2, c4);
  c4 = __builtin_fma (c8, x4, c4);
  // multiply c4 by x and add P[3]
  a_mul (h, l, c4, x);
  double t;
  fast_two_sum (h, &t, P[3], *h);
  t += *l;
  // multiply (h,t) by x and add P[2]
  a_mul (h, l, *h, x);
  *l = __builtin_fma (t, x, *l);
  fast_two_sum (h, &t, P[2], *h);
  t += *l;
  // multiply (h,t) by x and add P[1]
  a_mul (h, l, *h, x);
  *l = __builtin_fma (t, x, *l);
  fast_two_sum (h, &t, P[1], *h);
  t += *l;
  // multiply (h,t) by x
  a_mul (h, l, *h, x);
  *l = __builtin_fma (t, x, *l);
  return 0x1.d4p-65; // 2^-64.13 < 0x1.d4p-65
}

/* Given -0x1.2b708872320e2p+5 < x < -0x1.6a09e667f3bccp-53 or
   0x1.6a09e667f3bccp-53 < x < 0x1.62e42fefa39fp+9, put in h + l a
   double-double approximation of expm1(x), and return the maximal
   corresponding absolute error. */
static double
expm1_fast (double *h, double *l, double x)
{
  b64u64_u t = {.f = x};
  // FIXME: pass ax from cr_expm1()
  uint64_t ux = t.u, ax = ux & 0x7ffffffffffffffflu;

  if (ax <= 0x3fc0000000000000lu) // |x| <= 0.125
    return expm1_fast_tiny (h, l, x);

  *h = -2;
  *l = 0;
  return 0;
}

double
cr_expm1 (double x)
{
  b64u64_u t = {.f = x};
  uint64_t ux = t.u, ax = ux & 0x7ffffffffffffffflu;

  if (__builtin_expect (ux >= 0xc042b708872320e2, 0))
  {
    // x = -NaN or x <= -0x1.2b708872320e2p+5
    if ((ux >> 52) == 0xfff) // -NaN or -Inf
      return (ux > 0xfff0000000000000lu) ? x : -1.0;
    // for x <= -0x1.2b708872320e2p+5, expm1(x) rounds to -1 to nearest
    return -1.0 + 0x1p-54;
  }
  else if (__builtin_expect (ax >= 0x40862e42fefa39f0, 0))
  {
    // x = +NaN or x >= 0x1.62e42fefa39fp+9
    if ((ux >> 52) == 0x7ff) // +NaN
      return x;
    // for x >= 0x1.62e42fefa39fp+9, expm1(x) rounds to +Inf to nearest
    return 0x1.fffffffffffffp+1023 + 0x1.fffffffffffffp+1023;
  }
  else if (ax <= 0x3ca6a09e667f3bcc) // |x| <= 0x1.6a09e667f3bccp-53
    /* then expm1(x) rounds to x (to nearest), with Taylor expansion
       x + x^2/2 + ... */
  {
    if (ax < 0x3ca0000000000000)
    {
      /* |x| < 0x1p-53: x^2 < 1/2 ulp(x), we have to deal with -0 apart
         since fma (-0, -0, -0) is (+0) + (-0) which evaluates to +0
         for some rounding modes */
      return (x == 0) ? x : __builtin_fma (x, x, x);
    }
    else
      /* 0x1p-53 <= |x| <= 0x1.6a09e667f3bccp-53: x/4 is exactly
         representable, and x^2/4 < 1/2 ulp(x) */
      return __builtin_fma (x, x * 0.25, x);
  }

  /* -0x1.2b708872320e2p+5 < x < -0x1.6a09e667f3bccp-53 or
     0x1.6a09e667f3bccp-53 < x < 0x1.62e42fefa39fp+9 */

  double err, h, l;
  err = expm1_fast (&h, &l, x);
  double left = h + __builtin_fma (err, -h, l);
  double right = h + __builtin_fma (err, h, l);
  if (x==TRACE) printf ("x=%la h=%la l=%la err=%la left=%la right=%la\n", x, h, l, err, left, right);
  if (left == right)
    return left;

  if (x==TRACE) printf ("fast path failed\n");

  return -2;
}
