/* Correctly rounded sinh for binary64 values.

Copyright (c) 2022-2023 INRIA.
Author: Paul Zimmermann.

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/* References:
   [1] IA-64 and Elementary Functions, Peter Markstein,
       Hewlett-Packard Professional Books, 2000, Chapter 16. */

#define TRACE 0x1.003a9d3e03c2p-20

#include <stdio.h>
#include <stdint.h>

typedef union { double f; uint64_t u; } d64u64;

/* Add a + b, such that *hi + *lo approximates a + b.
   Assumes |a| >= |b|.  */
static void
fast_two_sum (double *hi, double *lo, double a, double b)
{
  double e;

  *hi = a + b;
  e = *hi - a; /* exact */
  *lo = b - e; /* exact */
  /* Now hi + lo = a + b exactly for rounding to nearest.
     For directed rounding modes, this is not always true.
     Take for example a = 1, b = 2^-200, and rounding up,
     then hi = 1 + 2^-52, e = 2^-52 (it can be proven that
     e is always exact), and lo = -2^52 + 2^-105, thus
     hi + lo = 1 + 2^-105 <> a + b = 1 + 2^-200.
     A bound on the error is given
     in "Note on FastTwoSum with Directed Roundings"
     by Paul Zimmermann, https://hal.inria.fr/hal-03798376, 2022.
     Theorem 1 says that
     the difference between a+b and hi+lo is bounded by 2u^2|a+b|
     and also by 2u^2|hi|. Here u=2^-53, thus we get:
     |(a+b)-(hi+lo)| <= 2^-105 min(|a+b|,|hi|) */
}

// Multiply exactly a and b, such that *hi + *lo = a * b.
static inline void a_mul(double *hi, double *lo, double a, double b) {
  *hi = a * b;
  *lo = __builtin_fma(a, b, -*hi);
}

/* Put in hi+lo an approximation of (ah+al)*(bh+bl) */
static inline void
d_mul (double *hi, double *lo, double ah, double al, double bh, double bl)
{
  double s, t;

  a_mul (hi, &s, ah, bh); /* exact */
  t = __builtin_fma (al, bh, s);
  *lo = __builtin_fma (ah, bl, t);
}

/* the following is a degree-13 odd polynomial approximating sinh(x)
   for |x| < 0.346574 generated by Sollya (see Psinh.sollya), with
   maximal relative error 2^-64.6 and maximal absolute error 2^-67.86 */
static const double S[] = {
  1,                     /* degree 1 */
  0x1.5555555555555p-3,  /* degree 3 */
  0x1.11111111112cep-7,  /* degree 5 */
  0x1.a01a019f46dbdp-13, /* degree 7 */
  0x1.71de3d4138905p-19, /* degree 9 */
  0x1.ae5a80cb87a71p-26, /* degree 11 */
  0x1.6e1355ff34e42p-33, /* degree 13 */
};

/* the following is a degree-12 even polynomial approximating cosh(x)
   for |x| < 0.346574 generated by Sollya (see Pcosh.sollya), with
   maximal relative error 2^-69.999 and maximal absolute error 2^-69.988 */
static const double C[] = {
  1,                     /* degree 0 */
  0x1p-1,                /* degree 2 */
  0x1.5555555555558p-5,  /* degree 4 */
  0x1.6c16c16c1500fp-10, /* degree 6 */
  0x1.a01a01ad74a7dp-16, /* degree 8 */
  0x1.27e4cc2e28096p-22, /* degree 10 */
  0x1.1f8ba76c9963ep-29, /* degree 12 */
};

/* put in h+l a double-double approximation of sinh(wh+wl),
   for |wh+wl| < 0.346574 */
static void
eval_S (double *h, double *l, double wh, double wl)
{
  double z = wh * wh;
  *h = S[6];
  *h = __builtin_fma (*h, z, S[5]);
  *h = __builtin_fma (*h, z, S[4]);
  *h = __builtin_fma (*h, z, S[3]);
  *h = __builtin_fma (*h, z, S[2]);
  *h = __builtin_fma (*h, z, S[1]);
  *h = __builtin_fma (*h, z, S[0]);
  *l = 0;
  /* multiply by wh+wl */
  *h *= wh;
}

/* put in h+l a double-double approximation of cosh(wh+wl),
   for |wh+wl| < 0.346574 */
static void
eval_C (double *h, double *l, double wh, double wl)
{
  double z = wh * wh;
  *h = C[6];
  *h = __builtin_fma (*h, z, C[5]);
  *h = __builtin_fma (*h, z, C[4]);
  *h = __builtin_fma (*h, z, C[3]);
  *h = __builtin_fma (*h, z, C[2]);
  *h = __builtin_fma (*h, z, C[1]);
  *h = __builtin_fma (*h, z, C[0]);
  *l = 0;
}

/* put in h+l a double-double approximation of sinh(x), for |x| < 2^10 */
static void
cr_sinh_fast (double *h, double *l, double x)
{
  /* We use the algorithm described in [1], Section 16.2:
     (1) write x = n*log(2) + w with |w| < log(2)/2
     (2) sinh(x) = sinh(n*log(2) + w)
                 = sinh(n*log(2))*cosh(w) + cosh(n*log(2))*sinh(w)
         where sinh(n*log(2)) = (2^n-2^-n)/2
               cosh(n*log(2)) = (2^n+2^-n)/2
         and cosh(w), sinh(w) are approximated by minimax polynomials
   */
  static const double inv_log2 = 0x1.71547652b82fep+0;
  /* |inv_log2 - 1/log(2)| < 2^-55.44 */
  static const double log2_h = 0x1.62e42fefa39efp-1;
  static const double log2_l = 0x1.abc9e3b39803fp-56;
  /* |log2_h + log2_l - log(2)| < 2^-110.43 */
  double n = __builtin_round (inv_log2 * x);
  if (x == TRACE) printf ("n=%f\n", n);
  /* since |x| < 2^10, |n| <= 1477,
     and |n - x/log(2)| <= |n-inv_log2*x| + |x|*|inv_log2-1/log(2)|
                        <= 1/2 + 2^10*2^-55.44 = 1/2 + 2^-45.44 */
  double wh, wl;
  a_mul (&wh, &wl, n, log2_h); /* exact */
  /* There can be no underflow nor overflow in the above a_mul().
     Moreover |wl| < ulp(wh| and |wh| < 1024 thus |wl| <= 2^-43 */
  wl = __builtin_fma (n, log2_l, wl);
  /* |n*log2_l+wl_in| < 1477*2^-55.25 + 2^-43 < 2^-42.61
     thus the rounding error on wl is bounded by ulp(2^-42.61) = 2^-95.
     This bounds the difference |wh + wl - n*(log2_h + log2_l)|. */

  /* |wh + wl - n*log(2)| <= |wh + wl - n*(log2_h + log2_l)|
                             + |n|*|log2_h + log2_l - log(2)|
                          <= 2^-95 + 1477*2^-110.43 < 2^-94.95 */

  /* thus |wh + wl| <= |wh + wl - n*log(2)| + |n*log(2)-x|
                    <= 2^-94.95 + log(2)*||n - x/log(2)|
                    <= 2^-94.95 + log(2)*(1/2 + 2^-45.44)
                    <= 0.346574 */
  
  /* approximate w = x - n*log(2) and renormalize:
     the subtraction x - wh is exact by Sterbenz theorem: either n=0,
     then wh=0, or |n| >= 1, then |x-n*log(2)| < log(2)/2 (approximatively)
     thus |x/(n*log(2)) - 1| < 1/(2n) */
  fast_two_sum (&wh, &wl, x - wh, -wl);
  if (x == TRACE) printf ("wh=%la wl=%la\n", wh, wl);

  double sh, sl, ch, cl;
  eval_S (&sh, &sl, wh, wl); /* accurate to 2^-61 (abs) */
  if (x == TRACE) printf ("sh=%la sl=%la\n", sh, sl);
  eval_C (&ch, &cl, wh, wl);
  if (x == TRACE) printf ("ch=%la cl=%la\n", ch, cl);

  double Sh, Sl, Ch, Cl;
  if (n < 0)
    n = -n;
  /* now n >= 0 */
  Ch = __builtin_ldexp (1.0, n - 1);  /* Ch >= 1/2 */
  Cl = __builtin_ldexp (1.0, -n - 1); /* Cl <= 1/2 */
  Sh = Ch;
  Sl = -Cl;
  fast_two_sum (&Ch, &Cl, Ch, Cl);
  fast_two_sum (&Sh, &Sl, Sh, Sl);

  double h1, l1, h2, l2;
  d_mul (&h1, &l1, Sh, Sl, ch, cl);
  d_mul (&h2, &l2, Ch, Cl, sh, sl);

  fast_two_sum (h, l, h1, h2);
  *l += l1 + l2;
  if (x == TRACE) printf ("h=%la l=%la\n", *h, *l);
}

#define MASK 0x7ffffffffffffffful /* to mask the sign bit */

double
cr_sinh (double x)
{
  d64u64 v = {.f = x};
  int e = ((v.u & MASK) >> 52) - 0x3ff;
  /* 2^(e-1) <= |x| < 2^e */

  if (e >= 11)
  {
    /* this will return NaN for x=NaN, Inf with the correct sign for x=+Inf
       or -Inf, and Inf/DBL_MAX or -Inf/-DBL_MAX for other |x| >= 2^10 */
    return x * 0x1p1023;
  }
  
  double h, l;
  cr_sinh_fast (&h, &l, x);
  return h + l;
}
