/* Correctly-rounded exp2m1 function for binary64 value.

Copyright (c) 2022-2023 Paul Zimmermann, Tom Hubrecht and Claude-Pierre Jeannerod

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// #define TRACE 0x1.638f4fcfa1cfbp+6 // 45 identical bits, RNDZ
#define TRACE 0x1.ffbb81681e9bap+9 // 46 identical bits, RNDZ

#include <stdio.h>
#include <stdint.h>
#include <math.h>

#define LN2H 0x1.62e42fefa39efp-1
#define LN2L 0x1.abc9e3b39803fp-56

/****************** code copied from pow.[ch] ********************************/

// Multiply exactly a and b, such that *hi + *lo = a * b.
static inline void a_mul(double *hi, double *lo, double a, double b) {
  *hi = a * b;
  *lo = __builtin_fma (a, b, -*hi);
}

// Multiply a double with a double double : a * (bh + bl)
static inline void s_mul (double *hi, double *lo, double a, double bh,
                          double bl) {
  a_mul (hi, lo, a, bh); /* exact */
  *lo = __builtin_fma (a, bl, *lo);
}

// Returns (ah + al) * (bh + bl) - (al * bl)
static inline void d_mul(double *hi, double *lo, double ah, double al,
                         double bh, double bl) {
  a_mul (hi, lo, ah, bh);
  *lo = __builtin_fma (ah, bl, *lo);
  *lo = __builtin_fma (al, bh, *lo);
}

// Add a + b, assuming |a| >= |b|
static inline void
fast_two_sum(double *hi, double *lo, double a, double b)
{
  double e;

  *hi = a + b;
  e = *hi - a; /* exact */
  *lo = b - e; /* exact */
}

// Add a + (bh + bl), assuming |a| >= |bh|
static inline void fast_sum(double *hi, double *lo, double a, double bh,
                            double bl) {
  fast_two_sum(hi, lo, a, bh);
  /* |(a+bh)-(hi+lo)| <= 2^-105 |hi| and |lo| < ulp(hi) */
  *lo += bl;
  /* |(a+bh+bl)-(hi+lo)| <= 2^-105 |hi| + ulp(lo),
     where |lo| <= ulp(hi) + |bl|. */
}

/* The following is a degree-4 polynomial generated by Sollya for exp(x)
   over [-0.000130273,0.000130273] with absolute error < 2^-74.346. */
static const double Q_1[] = {0x1p0,                 /* degree 0 */
                             0x1p0,                 /* degree 1 */
                             0x1p-1,                /* degree 2 */
                             0x1.5555555995d37p-3,  /* degree 3 */
                             0x1.55555558489dcp-5   /* degree 4 */
};

// Approximation for the fast path of exp(z) for z=zh+zl,
// with |z| < 0.000130273 < 2^-12.88 and |zl| < 2^-42.6
// (assuming x^y does not overflow or underflow)
static inline void q_1 (double *hi, double *lo, double zh, double zl) {
  double z = zh + zl;
  double q = __builtin_fma (Q_1[4], zh, Q_1[3]);

  q = __builtin_fma (q, z, Q_1[2]);

  fast_two_sum (hi, lo, Q_1[1], q * z);

  d_mul (hi, lo, zh, zl, *hi, *lo);

  fast_sum (hi, lo, Q_1[0], *hi, *lo);
}

/* For 0 <= i < 64, T1[i] = (h,l) such that h+l is the best double-double
   approximation of 2^(i/64). The approximation error is bounded as follows:
   |h + l - 2^(i/64)| < 2^-107. */
static const double T1[][2] = {
    {              0x1p+0,                 0x0p+0},
    {0x1.02c9a3e778061p+0, -0x1.19083535b085dp-56},
    {0x1.059b0d3158574p+0,  0x1.d73e2a475b465p-55},
    {0x1.0874518759bc8p+0,  0x1.186be4bb284ffp-57},
    {0x1.0b5586cf9890fp+0,  0x1.8a62e4adc610bp-54},
    {0x1.0e3ec32d3d1a2p+0,  0x1.03a1727c57b53p-59},
    {0x1.11301d0125b51p+0, -0x1.6c51039449b3ap-54},
    { 0x1.1429aaea92dep+0, -0x1.32fbf9af1369ep-54},
    {0x1.172b83c7d517bp+0, -0x1.19041b9d78a76p-55},
    {0x1.1a35beb6fcb75p+0,  0x1.e5b4c7b4968e4p-55},
    {0x1.1d4873168b9aap+0,  0x1.e016e00a2643cp-54},
    {0x1.2063b88628cd6p+0,  0x1.dc775814a8495p-55},
    {0x1.2387a6e756238p+0,  0x1.9b07eb6c70573p-54},
    {0x1.26b4565e27cddp+0,  0x1.2bd339940e9d9p-55},
    {0x1.29e9df51fdee1p+0,  0x1.612e8afad1255p-55},
    {0x1.2d285a6e4030bp+0,  0x1.0024754db41d5p-54},
    {0x1.306fe0a31b715p+0,  0x1.6f46ad23182e4p-55},
    {0x1.33c08b26416ffp+0,  0x1.32721843659a6p-54},
    {0x1.371a7373aa9cbp+0, -0x1.63aeabf42eae2p-54},
    {0x1.3a7db34e59ff7p+0, -0x1.5e436d661f5e3p-56},
    {0x1.3dea64c123422p+0,  0x1.ada0911f09ebcp-55},
    {0x1.4160a21f72e2ap+0, -0x1.ef3691c309278p-58},
    {0x1.44e086061892dp+0,   0x1.89b7a04ef80dp-59},
    { 0x1.486a2b5c13cdp+0,   0x1.3c1a3b69062fp-56},
    {0x1.4bfdad5362a27p+0,  0x1.d4397afec42e2p-56},
    {0x1.4f9b2769d2ca7p+0, -0x1.4b309d25957e3p-54},
    {0x1.5342b569d4f82p+0, -0x1.07abe1db13cadp-55},
    {0x1.56f4736b527dap+0,  0x1.9bb2c011d93adp-54},
    {0x1.5ab07dd485429p+0,  0x1.6324c054647adp-54},
    {0x1.5e76f15ad2148p+0,  0x1.ba6f93080e65ep-54},
    {0x1.6247eb03a5585p+0, -0x1.383c17e40b497p-54},
    {0x1.6623882552225p+0, -0x1.bb60987591c34p-54},
    {0x1.6a09e667f3bcdp+0, -0x1.bdd3413b26456p-54},
    {0x1.6dfb23c651a2fp+0, -0x1.bbe3a683c88abp-57},
    {0x1.71f75e8ec5f74p+0, -0x1.16e4786887a99p-55},
    {0x1.75feb564267c9p+0, -0x1.0245957316dd3p-54},
    {0x1.7a11473eb0187p+0, -0x1.41577ee04992fp-55},
    {0x1.7e2f336cf4e62p+0,  0x1.05d02ba15797ep-56},
    {0x1.82589994cce13p+0, -0x1.d4c1dd41532d8p-54},
    {0x1.868d99b4492edp+0, -0x1.fc6f89bd4f6bap-54},
    {0x1.8ace5422aa0dbp+0,  0x1.6e9f156864b27p-54},
    {0x1.8f1ae99157736p+0,  0x1.5cc13a2e3976cp-55},
    {0x1.93737b0cdc5e5p+0, -0x1.75fc781b57ebcp-57},
    { 0x1.97d829fde4e5p+0, -0x1.d185b7c1b85d1p-54},
    { 0x1.9c49182a3f09p+0,  0x1.c7c46b071f2bep-56},
    {0x1.a0c667b5de565p+0, -0x1.359495d1cd533p-54},
    {0x1.a5503b23e255dp+0, -0x1.d2f6edb8d41e1p-54},
    {0x1.a9e6b5579fdbfp+0,  0x1.0fac90ef7fd31p-54},
    {0x1.ae89f995ad3adp+0,  0x1.7a1cd345dcc81p-54},
    {0x1.b33a2b84f15fbp+0, -0x1.2805e3084d708p-57},
    {0x1.b7f76f2fb5e47p+0, -0x1.5584f7e54ac3bp-56},
    {0x1.bcc1e904bc1d2p+0,  0x1.23dd07a2d9e84p-55},
    {0x1.c199bdd85529cp+0,  0x1.11065895048ddp-55},
    {0x1.c67f12e57d14bp+0,  0x1.2884dff483cadp-54},
    {0x1.cb720dcef9069p+0,  0x1.503cbd1e949dbp-56},
    {0x1.d072d4a07897cp+0, -0x1.cbc3743797a9cp-54},
    {0x1.d5818dcfba487p+0,  0x1.2ed02d75b3707p-55},
    {0x1.da9e603db3285p+0,  0x1.c2300696db532p-54},
    {0x1.dfc97337b9b5fp+0, -0x1.1a5cd4f184b5cp-54},
    {0x1.e502ee78b3ff6p+0,  0x1.39e8980a9cc8fp-55},
    {0x1.ea4afa2a490dap+0, -0x1.e9c23179c2893p-54},
    {0x1.efa1bee615a27p+0,   0x1.dc7f486a4b6bp-54},
    { 0x1.f50765b6e454p+0,  0x1.9d3e12dd8a18bp-54},
    {0x1.fa7c1819e90d8p+0,  0x1.74853f3a5931ep-55},
};

/* For 0 <= i < 64, T2[i] = (h,l) such that h+l is the best double-double
   approximation of 2^(i/2^12). The approximation error is bounded as follows:
   |h + l - 2^(i/2^12)| < 2^-107. */
static const double T2[][2] = {
    {              0x1p+0,                 0x0p+0},
    {0x1.000b175effdc7p+0,  0x1.ae8e38c59c72ap-54},
    {0x1.00162f3904052p+0, -0x1.7b5d0d58ea8f4p-58},
    {0x1.0021478e11ce6p+0,  0x1.4115cb6b16a8ep-54},
    {0x1.002c605e2e8cfp+0, -0x1.d7c96f201bb2fp-55},
    {0x1.003779a95f959p+0,  0x1.84711d4c35e9fp-54},
    {0x1.0042936faa3d8p+0, -0x1.0484245243777p-55},
    { 0x1.004dadb113dap+0, -0x1.4b237da2025f9p-54},
    {0x1.0058c86da1c0ap+0, -0x1.5e00e62d6b30dp-56},
    {0x1.0063e3a559473p+0,  0x1.a1d6cedbb9481p-54},
    {0x1.006eff583fc3dp+0, -0x1.4acf197a00142p-54},
    {0x1.007a1b865a8cap+0, -0x1.eaf2ea42391a5p-57},
    {0x1.0085382faef83p+0,  0x1.da93f90835f75p-56},
    {0x1.00905554425d4p+0, -0x1.6a79084ab093cp-55},
    {0x1.009b72f41a12bp+0,  0x1.86364f8fbe8f8p-54},
    {0x1.00a6910f3b6fdp+0, -0x1.82e8e14e3110ep-55},
    {0x1.00b1afa5abcbfp+0, -0x1.4f6b2a7609f71p-55},
    {0x1.00bcceb7707ecp+0, -0x1.e1a258ea8f71bp-56},
    {0x1.00c7ee448ee02p+0,  0x1.4362ca5bc26f1p-56},
    {0x1.00d30e4d0c483p+0,  0x1.095a56c919d02p-54},
    {0x1.00de2ed0ee0f5p+0, -0x1.406ac4e81a645p-57},
    { 0x1.00e94fd0398ep+0,  0x1.b5a6902767e09p-54},
    {0x1.00f4714af41d3p+0, -0x1.91b2060859321p-54},
    {0x1.00ff93412315cp+0,  0x1.427068ab22306p-55},
    {0x1.010ab5b2cbd11p+0,  0x1.c1d0660524e08p-54},
    {0x1.0115d89ff3a8bp+0, -0x1.e7bdfb3204be8p-54},
    {0x1.0120fc089ff63p+0,  0x1.843aa8b9cbbc6p-55},
    {0x1.012c1fecd613bp+0, -0x1.34104ee7edae9p-56},
    {0x1.0137444c9b5b5p+0, -0x1.2b6aeb6176892p-56},
    {0x1.01426927f5278p+0,  0x1.a8cd33b8a1bb3p-56},
    {0x1.014d8e7ee8d2fp+0,  0x1.2edc08e5da99ap-56},
    {0x1.0158b4517bb88p+0,  0x1.57ba2dc7e0c73p-55},
    {0x1.0163da9fb3335p+0,  0x1.b61299ab8cdb7p-54},
    {0x1.016f0169949edp+0, -0x1.90565902c5f44p-54},
    {0x1.017a28af25567p+0,  0x1.70fc41c5c2d53p-55},
    {0x1.018550706ab62p+0,  0x1.4b9a6e145d76cp-54},
    {0x1.019078ad6a19fp+0, -0x1.008eff5142bf9p-56},
    {0x1.019ba16628de2p+0, -0x1.77669f033c7dep-54},
    {0x1.01a6ca9aac5f3p+0, -0x1.09bb78eeead0ap-54},
    {0x1.01b1f44af9f9ep+0,  0x1.371231477ece5p-54},
    {0x1.01bd1e77170b4p+0,  0x1.5e7626621eb5bp-56},
    {0x1.01c8491f08f08p+0, -0x1.bc72b100828a5p-54},
    { 0x1.01d37442d507p+0, -0x1.ce39cbbab8bbep-57},
    {0x1.01de9fe280ac8p+0,  0x1.16996709da2e2p-55},
    {0x1.01e9cbfe113efp+0, -0x1.c11f5239bf535p-55},
    {0x1.01f4f8958c1c6p+0,  0x1.e1d4eb5edc6b3p-55},
    {0x1.020025a8f6a35p+0, -0x1.afb99946ee3fp-54},
    {0x1.020b533856324p+0, -0x1.8f06d8a148a32p-54},
    {0x1.02168143b0281p+0, -0x1.2bf310fc54eb6p-55},
    {0x1.0221afcb09e3ep+0, -0x1.c95a035eb4175p-54},
    {0x1.022cdece68c4fp+0, -0x1.491793e46834dp-54},
    {0x1.02380e4dd22adp+0, -0x1.3e8d0d9c49091p-56},
    {0x1.02433e494b755p+0, -0x1.314aa16278aa3p-54},
    {0x1.024e6ec0da046p+0,  0x1.48daf888e9651p-55},
    {0x1.02599fb483385p+0,  0x1.56dc8046821f4p-55},
    {0x1.0264d1244c719p+0,  0x1.45b42356b9d47p-54},
    {0x1.027003103b10ep+0, -0x1.082ef51b61d7ep-56},
    {0x1.027b357854772p+0,  0x1.2106ed0920a34p-56},
    {0x1.0286685c9e059p+0, -0x1.fd4cf26ea5d0fp-54},
    {0x1.02919bbd1d1d8p+0, -0x1.09f8775e78084p-54},
    {0x1.029ccf99d720ap+0,  0x1.64cbba902ca27p-58},
    {0x1.02a803f2d170dp+0,  0x1.4383ef231d207p-54},
    {0x1.02b338c811703p+0,  0x1.4a47a505b3a47p-54},
    {0x1.02be6e199c811p+0,  0x1.e47120223467fp-54},
};

typedef union {
  double f;
  uint64_t u;
} f64_u;

/*
  Approximation of exp(x), where x = xh + xl

  exp(x) is approximated by hi + lo.

  For the error analysis, we only consider the case where x^y does not
  overflow or underflow. We get:

  (hi + lo) / exp(xh + xl) = 1 + eps with |eps| < 2^-74.139

  Assumes |xl/xh| < 2^-23.89 and |xl| < 2^-14.3486.

  See analysis before the exp_1() call in cr_pow(), which proves
  |rl| < 2^-23.89 |rh| (here xh=rh and xl=rl).

  At output, we also have 0.99985 < hi+lo < 1.99995 and |lo/hi| < 2^-41.4.
*/

static inline void exp_1 (double *hi, double *lo, double xh, double xl) {

#define INVLOG2 0x1.71547652b82fep+12 /* |INVLOG2-2^12/log(2)| < 2^-43.4 */
  double k = __builtin_roundeven (xh * INVLOG2);

  double kh, kl;
#define LOG2H 0x1.62e42fefa39efp-13
#define LOG2L 0x1.abc9e3b39803fp-68
  s_mul (&kh, &kl, k, LOG2H, LOG2L);

  double yh, yl;
  fast_two_sum (&yh, &yl, xh - kh, xl);
  yl -= kl;

  int64_t K = k; /* Note: k is an integer, this is just a conversion. */
  int64_t M = (K >> 12) + 0x3ff;
  int64_t i2 = (K >> 6) & 0x3f;
  int64_t i1 = K & 0x3f;

  double t1h = T1[i2][0], t1l = T1[i2][1], t2h = T2[i1][0], t2l = T2[i1][1];
  d_mul (hi, lo, t2h, t2l, t1h, t1l);

  double qh, ql;
  q_1 (&qh, &ql, yh, yl);

  d_mul (hi, lo, *hi, *lo, qh, ql);

  f64_u _d;

  _d.u = M << 52;
  *hi *= _d.f;
  *lo *= _d.f;
}

/****************** end of code copied from pow.[ch] *************************/

/****************** code copied from expm1.c *********************************/

/* The following is a degree-7 polynomial generated by Sollya for exp(z)
   over [-0.000130273,0.000130273] with absolute error < 2^-113.218
   (see file exp_accurate.sollya). Since we use this code only for
   |x| > 0.125 in exp2m1(x), the corresponding relative error for exp2m1
   is about 2^-113.218/|exp2m1(-0.125)| which is about 2^-110. */
static const double Q_2[] = {
  0x1p0, // degree 0, Q_2[0]
  0x1p0, // degree 1, Q_2[1]
  0x1p-1, // degree 2, Q_2[2]
  0x1.5555555555555p-3, 0x1.55555555c4d26p-57, // degree 3, Q_2[3], Q_2[4]
  0x1.5555555555555p-5, // degree 4, Q_2[5]
  0x1.1111111111111p-7, // degree 5, Q_2[6]
  0x1.6c16c3fbb4213p-10, // degree 6, Q_2[7]
  0x1.a01a023ede0d7p-13, // degree 7, Q_2[8]
};

// Approximation for the accurate path of exp(z) for z=zh+zl,
// with |z| < 0.000130273 < 2^-12.88 and |zl| < 2^-42.6
// (assuming x^y does not overflow or underflow)
static inline void q_2 (double *hi, double *lo, double zh, double zl) {
  /* Let q[0]..q[7] be the coefficients of degree 0..7 of Q_2.
     The ulp of q[7]*z^7 is at most 2^-155, thus we can compute q[7]*z^7
     in double precision only.
     The ulp of q[6]*z^6 is at most 2^-139, thus we can compute q[6]*z^6
     in double precision only.
     The ulp of q[5]*z^5 is at most 2^-124, thus we can compute q[5]*z^5
     in double precision only. */
  double z = zh + zl;
  double q = __builtin_fma (Q_2[8], zh, Q_2[7]);

  q = __builtin_fma (q, z, Q_2[6]);

  q = __builtin_fma (q, z, Q_2[5]);

  // multiply q by z and add Q_2[3] + Q_2[4]
  a_mul (hi, lo, q, z);
  double t;
  fast_two_sum (hi, &t, Q_2[3], *hi);
  *lo += t + Q_2[4];

  // multiply hi+lo by zh+zl and add Q_2[2]
  d_mul (hi, lo, *hi, *lo, zh, zl);
  fast_two_sum (hi, &t, Q_2[2], *hi);
  *lo += t;

  // multiply hi+lo by zh+zl and add Q_2[1]
  d_mul (hi, lo, *hi, *lo, zh, zl);
  fast_two_sum (hi, &t, Q_2[1], *hi);
  *lo += t;

  // multiply hi+lo by zh+zl and add Q_2[0]
  d_mul (hi, lo, *hi, *lo, zh, zl);
  fast_two_sum (hi, &t, Q_2[0], *hi);
  *lo += t;
}

/* we have |xl| <= ulp(xh) (up to a factor of 2), and since |xh| < 2^9.48,
   this yields |xl| <= 2^-43 */
static inline void exp_2 (double *hi, double *lo, double xh, double xl) {

  int bug = xh == 0x1.1d1704536a6b6p+0 && xl == 0x1.0e9390977ee67p-53;
#define INVLOG2 0x1.71547652b82fep+12 /* |INVLOG2-2^12/log(2)| < 2^-43.4 */
  double k = __builtin_roundeven (xh * INVLOG2);
  // since x <= 0x1.62e42fefa39fp+9 we have k <= 4194305

  double yh, yl;
#define LOG2Hacc 0x1.62e42ffp-13
#define LOG2Macc -0x1.718432a1b0e26p-47
#define LOG2Lacc -0x1.9ff0342542fc3p-102
  yh = __builtin_fma (-k, LOG2Hacc, xh); // exact, |yh| < 2^-13.5
  a_mul (hi, lo, -k, LOG2Macc);          // exact, |hi| < 2^-24.4
  // we have |lo| <= ulp(hi) <= 2^-77 */
  if (__builtin_fabs (yh) >= __builtin_fabs (*hi))
    fast_two_sum (&yh, &yl, yh, *hi);
  else
    fast_two_sum (&yh, &yl, *hi, yh);
  /* |yh| < 2^-13.4, |yl| <= ulp(yh) <= 2^-66 */
  /* now yh+yl+lo approximates xh - k*(LOG2Hacc + LOG2Macc),
     with error bounded by 2^-105*|yh| < 2^-118.4 */
  // we then add the lower term from -k*LOG2Macc and -k*LOG2Lacc
  yl += __builtin_fma (-k, LOG2Lacc, *lo);
  /* it remains to add xl, but xl can contribute to yh, thus we use a
     fast two sum again */
  if (__builtin_fabs (yh) >= __builtin_fabs (xl))
    fast_two_sum (&yh, lo, yh, xl);
  else
    fast_two_sum (&yh, lo, xl, yh);
  yl += *lo;

  int64_t K = k;
  int64_t M = (K >> 12) + 0x3ff;
  int64_t i2 = (K >> 6) & 0x3f;
  int64_t i1 = K & 0x3f;

  double t1h = T1[i2][0], t1l = T1[i2][1], t2h = T2[i1][0], t2l = T2[i1][1];
  d_mul (hi, lo, t2h, t2l, t1h, t1l);

  double qh, ql;
  q_2 (&qh, &ql, yh, yl);

  d_mul (hi, lo, *hi, *lo, qh, ql);
  f64_u _d;

  _d.u = M << 52;
  *hi *= _d.f;
  *lo *= _d.f;
}

/****************** end of code copied from expm1.c **************************/

typedef union {double f; uint64_t u;} b64u64_u;

/* The following is a degree-12 polynomial generated by Sollya
   (file exp2m1_fast.sollya),
   which approximates exp2m1(x) with relative error bounded by 2^-68.559
   for |x| <= 0.125. */
static const double P[] = {
  0x1.62e42fefa39efp-1, 0x1.abd1697afcaf8p-56,  // degree 1, P[0], P[1]
  0x1.ebfbdff82c58fp-3, -0x1.5e5a1d09e1599p-57, // degree 2, P[2], P[3]
  0x1.c6b08d704a0bfp-5,  // degree 3, P[4]
  0x1.3b2ab6fba4e78p-7,  // degree 4, P[5]
  0x1.5d87fe78a84e6p-10, // degree 5, P[6]
  0x1.430912f86a48p-13,  // degree 6, P[7]
  0x1.ffcbfbc1f2b36p-17, // degree 7, P[8]
  0x1.62c0226c7f6d1p-20, // degree 8, P[9]
  0x1.b539529819e63p-24, // degree 9, P[10]
  0x1.e4d552bed5b9cp-28, // degree 10, P[11]
};

/* |x| <= 0.125, put in h + l a double-double approximation of exp2m1(x),
   and return the maximal corresponding absolute error.
   We also have |x| > 0x1.0527dbd87e24dp-51.
   With xmin=RR("0x1.0527dbd87e24dp-51",16), the routine
   exp2m1_fast_tiny_all(xmin,0.125,2^-65.63) in exp2m1.sage returns
   1.74952121608842e-20 < 2^-65.63, and
   exp2m1_fast_tiny_all(-0.125,-xmin,2^-65.54) returns
   1.86402194391062e-20 < 2^-65.54, which proves the relative
   error is bounded by 2^-65.54. */
static double
exp2m1_fast_tiny (double *h, double *l, double x)
{
  /* The maximal value of |P[4]*x^4/exp2m1(x)| over [-0.125,0.125]
     is less than 2^-15.109, thus we can compute the coefficients of degree
     4 or higher using double precision only. */
  double x2 = x * x, x4 = x2 * x2;
  double c8 = __builtin_fma (P[10], x, P[9]); // degree 8
  double c6 = __builtin_fma (P[8], x, P[7]);  // degree 6
  double c4 = __builtin_fma (P[6], x, P[5]);  // degree 4
  c8 = __builtin_fma (P[11], x2, c8);         // degree 8
  c4 = __builtin_fma (c6, x2, c4);            // degree 4
  c4 = __builtin_fma (c8, x4, c4);            // degree 4
  double t;
  // multiply c4 by x and add P[4]
  a_mul (h, l, c4, x);
  fast_two_sum (h, &t, P[4], *h);
  *l += t;
  // multiply (h,l) by x and add P[2]+P[3]
  s_mul (h, l, x, *h, *l);
  fast_two_sum (h, &t, P[2], *h);
  *l += t + P[3];
  // multiply (h,l) by x and add P[0]+P[1]
  s_mul (h, l, x, *h, *l);
  fast_two_sum (h, &t, P[0], *h);
  *l += t + P[1];
  // multiply (h,l) by x
  s_mul (h, l, x, *h, *l);
  return 0x1.61p-66 * *h; // 2^-65.54 < 0x1.61p-66
}

/* Given -54 < x < -0x1.0527dbd87e24dp-51 or
   0x1.0527dbd87e24dp-51 < x < 1024, put in h + l a
   double-double approximation of exp2m1(x), and return the maximal
   corresponding absolute error.
   The input tiny is true iff |x| <= 0.125. */
static double
exp2m1_fast (double *h, double *l, double x, int tiny)
{
  if (tiny) // |x| <= 0.125
    return exp2m1_fast_tiny (h, l, x);

  /* now -54 < x < -0.125 or 0.125 < x < 1024: we approximate exp(x*log(2))
     and subtract 1 */
  s_mul (h, l, x, LN2H, LN2L);
  /* s_mul (h, l, x, LN2H, LN2L) decomposes into:
     a_mul (h, t, x, LN2H)
     l += fma (x, LN2L, t)
     The a_mul() call is exact, and the error of the fma() is bounded by
     ulp(l).
     We have |t| <= ulp(h) <= ulp(LN2H*1024) = 2^-43,
     |t+x*LN2L| <= 2^-43 * 1024*LN2L < 2^-42.7,
     thus |l| <= |t| + |x*LN2L| + ulp(t+x*LN2L)
              <= 2^-42.7 + 2^-95 <= 2^-42.6, and ulp(l) <= 2^-95.
     Thus:
     |h + l - x*log(2)| <= |h + l - x*(LN2H+LN2L)| + |x|*|LN2H+LN2L-log(2)|
                        <= 2^-95 + 1024*2^-110.4 < 2^-94.9 */
  exp_1 (h, l, *h, *l);
  /* h_out + l_out = exp(h + l) * (1 + eps) with |eps| < 2^-74.139
                   = exp(x*log(2) + eps0) * (1 + eps)
                   with |eps0| < 2^-94.9 and |eps| < 2^-74.139
                   = 2^x * (1 + eps1) with |eps1| < 2^-74.138 */
  double u;
  if (x >= 0) // implies h >= 1 and the fast_two_sum pre-condition holds
    fast_two_sum (h, &u, *h, -1.0);
  else
    fast_two_sum (h, &u, -1.0, *h); // x < 0 thus h <= 1
  *l += u;
  /* The error in the above fast_two_sum is bounded by 2^-105*|h|,
     with the new value of h, thus the total absolute error is bounded
     by eps1*|h_in|+2^-105*|h|.
     Relatively to h this yields eps1*|h_in/h| + 2^-105, where the maximum
     of |h_in/h| is obtained for x near -0.125, with |2^x/(2^x-1)| < 11.05.
     We get a relative error bound of 2^-74.138*11.05 + 2^-105 < 2^-70.67. */
  return 0x1.42p-71 * *h; /* 2^-70.67 < 0x1.42p-71 */
}

/* The following is a degree-15 polynomial generated by Sollya
   (file exp2m1_accurate.sollya),
   which approximates exp2m1(x) with relative error bounded by 2^-107.666
   for |x| <= 0.125. */
static const double Q[] = {
  0x1.62e42fefa39efp-1, 0x1.abc9e3b39804p-56,    // degree 1: Q[0], Q[1]
  0x1.ebfbdff82c58fp-3, -0x1.5e43a53e44dcfp-57,  // degree 2: Q[2], Q[3]
  0x1.c6b08d704a0cp-5, -0x1.d331627517168p-59,   // degree 3: Q[4], Q[5]
  0x1.3b2ab6fba4e77p-7, 0x1.4e65df0779f8cp-62,   // degree 4: Q[6], Q[7]
  0x1.5d87fe78a6731p-10, 0x1.0717fbf4bd05p-66,   // degree 5: Q[8], Q[9]
  0x1.430912f86c787p-13, 0x1.bd2bdec9bcd42p-67,  // degree 6: Q[10], Q[11]
  0x1.ffcbfc588b0c7p-17, -0x1.e60aa6d5e4aa9p-71, // degree 7: Q[12], Q[13]
  0x1.62c0223a5c824p-20,                         // degree 8: Q[14]
  0x1.b5253d395e7d4p-24,                         // degree 9: Q[15]
  0x1.e4cf5158b916p-28,                          // degree 10: Q[16]
  0x1.e8cac734c6058p-32,                         // degree 11: Q[17]
  0x1.c3bd64f17199dp-36,                         // degree 12: Q[18]
  0x1.8161a17e05651p-40,                         // degree 13: Q[19]
  0x1.3150b3d792231p-44,                         // degree 14: Q[20]
  0x1.c184260bfad7ep-49,                         // degree 15: Q[21]
};

/* Accurate path for 0x1.0527dbd87e24dp-51 < |x| <= 0.125. */
static double
exp2m1_accurate_tiny (double x)
{
  /* the following exceptional cases have at least 51 identical bits after
     the round bit, thus are hard to correctly round with double-double
     arithmetic */
#define EXCEPTIONS 59
  static const double exceptions[EXCEPTIONS][3] = {
    {-0x1.2716da024f6d9p-50, -0x1.9914a112c8dadp-51, 0x1.004287d8393fep-159},
    {0x1.29d3990338b4ep-50, 0x1.9ce011cf5f46ep-51, -0x1.ba552cb13d27bp-161},
    {0x1.4bbbd21c8c721p-51, 0x1.cbe169f09f95ep-52, -0x1.256d63281c5efp-158},
    {-0x1.0e5678a7b8bap-47, -0x1.76c48a7a527bp-48, -0x1.6fbb13d1e3faap-155},
    {-0x1.3b6203ff2cbe6p-29, -0x1.b536a7dace8cap-30, 0x1.07bb47158694fp-137},
    {-0x1.66ff2474821a7p-44, -0x1.f1accede78f51p-45, -0x1.fffffffffffffp-99},
    {-0x1.0f1c08e43f217p-20, -0x1.77d66368613b4p-21, 0x1.0d3de71c269fcp-130},
    {-0x1.ba24ff5dea796p-34, -0x1.3278a26ed0162p-34, 0x1.f837135341102p-142},
    {-0x1.41e4bec9bc547p-19, -0x1.be3d238468f35p-20, -0x1.fffffffffffffp-74},
    {-0x1.bfb3efcdf2bc4p-10, -0x1.3623eff91de91p-10, 0x1.cd506bd8d0439p-117},
    {-0x1.9b28778a9a8a3p-4, -0x1.134dec3a6324bp-4, -0x1.1acaaac7e1ff7p-110},
    {-0x1.922076a30742p-24, -0x1.16bba98a001c1p-24, 0x1.d90eddeada3e4p-133},
    {-0x1.e07a2fbc7fd84p-30, -0x1.4d0a9e634dc35p-30, -0x1.fffffffffffffp-84},
    {-0x1.8288f6bb77d79p-23, -0x1.0becf6ad924bfp-23, -0x1.fffffffffffffp-77},
    {-0x1.d091d774b141ep-35, -0x1.4203e2685b069p-35, -0x1.a166cdf05ff79p-143},
    {-0x1.f6ec73d3948c3p-4, -0x1.4e2d8b0cead45p-4, -0x1.40f3d5244acffp-109},
    {-0x1.6f94484e5e1fdp-5, -0x1.f5baee010ccc6p-6, -0x1.3298bcde4f9a8p-115},
    {-0x1.3918e8608bd5bp-8, -0x1.b153bf52832f9p-9, -0x1.fffffffffffffp-63},
    {-0x1.a6d6a49f2187fp-50, -0x1.2516dafdf17adp-50, -0x1.85a87dc0b88p-157},
    {-0x1.daaead688f65fp-45, -0x1.4906541fb8d5cp-45, -0x1.31de54e6dc4ep-151},
    {-0x1.bfc1e9b0f73aep-35, -0x1.365ca0d933491p-35, -0x1.fffffffffffffp-89},
    {-0x1.98aae9950914ep-19, -0x1.1b443a4805f8fp-19, 0x1.fffffffffffffp-73},
    {-0x1.0d296993d1368p-20, -0x1.752326c780f68p-21, 0x1.1cade8dbbd5d8p-130},
    {-0x1.7b388eb924102p-18, -0x1.06dafba21afffp-18, 0x1.fffffffffffffp-72},
    {-0x1.3b6786a5a9a69p-17, -0x1.b53dee1a96ca4p-18, -0x1.282e0781f97f5p-124},
    {-0x1.8474969f5eb14p-9, -0x1.0cfafc07a957bp-9, -0x1.fffffffffffffp-63},
    {-0x1.a1f242e670d73p-42, -0x1.21b2c54479c4dp-42, 0x1.48a5d173822e8p-150},
    {-0x1.3c7971b0ee205p-14, -0x1.b6b716c4bb87cp-15, 0x1.d7150e84d973dp-121},
    {-0x1.0867d8153350dp-9, -0x1.6e49b44e387f5p-10, -0x1.fffffffffffffp-64},
    {-0x1.0c3ebbd1a501fp-11, -0x1.73ccf8ee62819p-12, 0x1.3a3965a926c6dp-120},
    {-0x1.0ee8225c19555p-23, -0x1.778e77e8b1e13p-24, -0x1.3da14df43e675p-129},
    {-0x1.3dbf41403c0b2p-15, -0x1.b87c37192e4f7p-16, 0x1.098861b427b13p-123},
    {-0x1.6d752e77a9dc2p-41, -0x1.faa1cb0d787b3p-42, -0x1.fffffffffffffp-96},
    {0x1.391609b20beaap-51, 0x1.b2078ba8f6835p-52, -0x1.85099d92fa919p-162},
    {-0x1.2c506b0368099p-51, -0x1.a052e3d5e791p-52, -0x1.428e13d1da7cap-159},
    {-0x1.3f596b7b1c5e2p-44, -0x1.bab64e105226ap-45, -0x1.1a2829f825272p-154},
    {0x1.02cdc0b0f314cp-37, 0x1.66c7342a5b89fp-38, -0x1.fffffffffffffp-92},
    {0x1.02df58d57f81fp-13, 0x1.66e3866f48983p-14, -0x1.3e42ea0bb96a5p-121},
    {0x1.1c4baf7475e2dp-23, 0x1.8a1e1272b4997p-24, 0x1.fffffffffffffp-78},
    {0x1.2162f23d082d5p-36, 0x1.912cc5483c4bbp-37, -0x1.9b93a2f7e5da4p-145},
    {0x1.2d664653786ecp-36, 0x1.a1d414c603907p-37, 0x1.fffffffffffffp-91},
    {0x1.3a6de04d8d384p-22, 0x1.b3e437cdb56dep-23, 0x1p-76},
    {0x1.3dc2574084694p-34, 0x1.b881f93d3d7bcp-35, 0x1.4d32033399826p-141},
    {0x1.4753a08baf7fbp-22, 0x1.c5c56aeb3c161p-23, 0x1.fffffffffffffp-77},
    {0x1.6a8ee6a3521fdp-6, 0x1.fa7ca1e176885p-7, 0x1.6530cb0e0ba64p-113},
    {0x1.8ff59817c7989p-9, 0x1.15862abd340e8p-9, 0x1.6ab813a41d504p-116},
    {0x1.a949818632705p-13, 0x1.26ceaaf78e39fp-13, -0x1.fffffffffffffp-67},
    {0x1.ac65fdb418f72p-40, 0x1.28f171f05f6fap-40, -0x1.51612679f6f55p-146},
    {0x1.b3665a468351p-35, 0x1.2dcbd0c2b922fp-35, -0x1.fffffffffffffp-89},
    {0x1.b6275c496a3d5p-16, 0x1.2fb5318232c0cp-16, 0x1.666c5e4de0763p-123},
    {0x1.b988be78bfb6bp-33, 0x1.320c53ed5fb63p-33, -0x1.fffffffffffffp-87},
    {0x1.c2ff91c241999p-47, 0x1.389bb3cfc42c2p-47, -0x1.023c49dbbc653p-154},
    {0x1.d4a8ebce833a3p-4, 0x1.52145769df4fbp-4, -0x1.5d8026da33cabp-111},
    {0x1.d57070df38af8p-50, 0x1.4563f61023f7p-50, -0x1.ac66c9a5a19p-157},
    {0x1.dcc98bad34bd4p-13, 0x1.4a82829ba33efp-13, 0x1.3a222409353fep-120},
    {0x1.e4c5c9414182ep-26, 0x1.5004cdd3ec269p-26, -0x1.411c828b7c78ep-133},
    {0x1.e755f4897c124p-27, 0x1.51cba0164bed2p-27, -0x1.16a01564a1359p-134},
    {0x1.f06778562781fp-38, 0x1.5814c6c101c7p-38, -0x1.333ad12f679a5p-145},
    {0x1.f6ac7a2928816p-49, 0x1.5c6d4854f6b3bp-49, 0x1.fffffffffffffp-103},
  };
  for (int i = 0; i < EXCEPTIONS; i++)
    if (x == exceptions[i][0])
      return exceptions[i][1] + exceptions[i][2];
#undef EXCEPTIONS

  double h, l, t;
  double x2 = x * x, x4 = x2 * x2;
  double c13 = __builtin_fma (Q[20], x, Q[19]); // degree 13
  double c11 = __builtin_fma (Q[18], x, Q[17]); // degree 11
  c13 = __builtin_fma (Q[21], x2, c13);         // degree 13
  // add Q[16]*x+c11*x2+c13*x4 to Q[15] (degree 9)
  fast_two_sum (&h, &l, Q[15], Q[16] * x + c11 * x2 + c13 * x4);
  // multiply h+l by x and add Q[14] (degree 8)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[14], h);
  l += t;
  // multiply h+l by x and add Q[12]+Q[13] (degree 7)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[12], h);
  l += t + Q[13];
  // multiply h+l by x and add Q[10]+Q[11] (degree 6)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[10], h);
  l += t + Q[11];
  // multiply h+l by x and add Q[8]+Q[9] (degree 5)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[8], h);
  l += t + Q[9];
  // multiply h+l by x and add Q[6]+Q[7] (degree 4)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[6], h);
  l += t + Q[7];
  // multiply h+l by x and add Q[4]+Q[5] (degree 3)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[4], h);
  l += t + Q[5];
  // multiply h+l by x and add Q[2]+Q[3] (degree 2)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[2], h);
  l += t + Q[3];
  // multiply h+l by x and add Q[0]+Q[1] (degree 2)
  s_mul (&h, &l, x, h, l);
  fast_two_sum (&h, &t, Q[0], h);
  l += t + Q[1];
  // multiply h+l by x
  s_mul (&h, &l, x, h, l);
  return h + l;
}

static double exp2m1_accurate (double x)
{
  b64u64_u t = {.f = x};
  uint64_t ux = t.u, ax = ux & 0x7ffffffffffffffflu;

  if (ax <= 0x3fc0000000000000lu) // |x| <= 0.125
    return exp2m1_accurate_tiny (x);

  /* now -54 < x < -0.125 or 0.125 < x < 1024: we approximate exp(x*log(2))
     and subtract 1 */

#define EXCEPTIONS 1
  static const double exceptions[EXCEPTIONS][3] = {
    {0x1.fffffffffffffp+9, 0x1.ffffffffffd3ap+1023, 0x1.bd0105c706c87p+968},
  };
  for (int i = 0; i < EXCEPTIONS; i++)
    if (x == exceptions[i][0])
      return exceptions[i][1] + exceptions[i][2];
#undef EXCEPTIONS

  double h, l;
  s_mul (&h, &l, x, LN2H, LN2L);
  if (x == TRACE) printf ("h=%la l=%la\n", h, l);
  exp_2 (&h, &l, h, l);
  if (x == TRACE) printf ("h=%la l=%la\n", h, l);
  double u;
  if (x >= 0) // implies h >= 1 and the fast_two_sum pre-condition holds
    fast_two_sum (&h, &u, h, -1.0);
  else
    fast_two_sum (&h, &u, -1.0, h); // x < 0 thus h <= 1
  l += u;
  /* the error in the above fast_two_sum is bounded by 2^-105*|h|,
     with the new value of h */
  return h + l;
}

double
cr_exp2m1 (double x)
{
  b64u64_u t = {.f = x};
  uint64_t ux = t.u, ax = ux & 0x7ffffffffffffffflu;

  if (__builtin_expect (ux >= 0xc04b000000000000lu, 0))
  {
    // x = -NaN or x <= -54
    if ((ux >> 52) == 0xfff) // -NaN or -Inf
      return (ux > 0xfff0000000000000lu) ? x : -1.0;
    // for x <= -54, exp2m1(x) rounds to -1 to nearest
    return -1.0 + 0x1p-54;
  }
  else if (__builtin_expect (ax >= 0x4090000000000000lu, 0))
  {
    // x = +NaN or x >= 1024
    if ((ux >> 52) == 0x7ff) // +NaN
      return x;
    // for x >= 1024, exp2m1(x) rounds to +Inf to nearest
    return 0x1.fffffffffffffp+1023 * x;
  }
  else if (ax <= 0x3cc0527dbd87e24dlu) // |x| <= 0x1.0527dbd87e24dp-51
    /* then the second term of the Taylor expansion of 2^x-1 at x=0 is
       smaller in absolute value than 1/2 ulp(first term):
       log(2)*x + log(2)^2*x^2/2 + ... */
  {
    double h, l;
    /* we use special code when log(2)*|x| < 2^-968, in which case
       the double-double approximation h+l has its lower part l
       "truncated" */
    if (ax <= 0x3771547652b82fe) // |x| <= 0x1.71547652b82fep-968
    {
      // special case for 0
      if (x == 0)
        return x;
      // scale x by 2^53
      x = x * 0x1p53;
      a_mul (&h, &l, LN2H, x);
      l = __builtin_fma (LN2L, x, l);
      double h2 = h + l; // round to 53-bit precision
      // scale back, hoping to avoid double rounding
      h2 = h2 * 0x1p-53;
      // now subtract back h2 * 2^53 from h to get the correction term
      h = __builtin_fma (-h2, 0x1p53, h);
      // add l
      h += l;
      // add h2 + h * 2^-53
      return __builtin_fma (h, 0x1p-53, h2);
    }
    else // 0x1.71547652b82fep-968 < |x| <= 0x1.0527dbd87e24dp-51
    {
      /* the following exceptional cases have at least 51 identical bits after
         the round bit, thus are hard to correctly round with double-double
         arithmetic */
#define EXCEPTIONS 60
      static const double exceptions[EXCEPTIONS][3] = {
        {0x1.d7430e6a40aap-78, 0x1.46a764f31c407p-78, 0x1.fffffffffffffp-132},
        {-0x1.e2b5692bd0c53p-80, -0x1.4e968fb1b5f41p-80, 0x1.fffffffffffffp-134},
        {0x1.9a8401f6d9784p-60, 0x1.1c8c3a93ce469p-60, -0x1.fffffffffffffp-114},
        {-0x1.5754d81696c42p-76, -0x1.dbf55aa9a7eb9p-77, -0x1.c81798a2dea9ep-184},
        {0x1.8ddd5485a342fp-56, 0x1.13c75940129cbp-56, 0x1.365292846d16p-164},
        {0x1.d622a201c030bp-52, 0x1.45df797393f11p-52, -0x1.cdcde906092cfp-159},
        {0x1.e704310d30238p-55, 0x1.5192f360cac0ap-55, 0x1.30562032a2c95p-161},
        {-0x1.d8bedc057858cp-65, -0x1.47aea7608c02bp-65, -0x1.ef8a5d5p-172},
        {-0x1.ec44ae4bc644p-74, -0x1.5536e12eb7335p-74, -0x1.fb8acp-181},
        {-0x1.f1bc3ef3e6f36p-65, -0x1.5900fbf46981dp-65, -0x1.fffffffffffffp-119},
        {-0x1.a16826a8e825dp-56, -0x1.21530a306cc85p-56, -0x1.38ac4a67cep-161},
        {-0x1.8c525b64ed08ep-59, -0x1.12b592f889516p-59, -0x1.7b71d1eep-169},
        {-0x1.bacdbd3005cd7p-60, -0x1.32ed98e196cf5p-60, -0x1.9b32a24b8p-166},
        {-0x1.0042796d534fdp-81, -0x1.6340571968b67p-82, -0x1.91fa30638e3b8p-188},
        {0x1.02f371449097fp-51, 0x1.66fb73eec9971p-52, 0x1.8d182ad6f54d8p-157},
        {-0x1.03eda6663a4b2p-70, -0x1.6856506d8234ap-71, -0x1.f48368854ffd7p-178},
        {-0x1.0481d96a2dfcap-61, -0x1.6923c31228cd3p-62, -0x1.59432bd8e301p-169},
        {0x1.086cbb0e900cfp-96, 0x1.6e920d043905ep-97, 0x1.0000000000001p-150},
        {-0x1.0c197520b26f4p-94, -0x1.73aa2cd72b7ccp-95, -0x1.1p-148},
        {-0x1.0e8e362e16fe6p-74, -0x1.7711d03d5c7bdp-75, -0x1.63020ffb5bda3p-181},
        {-0x1.0ede4c1293a9bp-59, -0x1.7780d5e5cf5c5p-60, -0x1.6b820f41efd9p-166},
        {0x1.101c8b0d7df57p-85, 0x1.793a04a8764ap-86, 0x1.95385b3628535p-194},
        {-0x1.103fc46963aafp-62, -0x1.796ad95f38488p-63, -0x1.efd4112076edap-170},
        {-0x1.19f9b6ddcc3e9p-84, -0x1.86e6a6125ee5fp-85, -0x1.d80acb1fd9a48p-191},
        {-0x1.1d65d5fc31246p-98, -0x1.8ba5360a2b553p-99, -0x1.0bee24969cff9p-204},
        {-0x1.1e3a6eaa49c6ep-84, -0x1.8ccbeeaab37e4p-85, 0x1p-138},
        {-0x1.241e7c1327b2ap-97, -0x1.94f6896c09e68p-98, -0x1.ad2fd62d965b7p-203},
        {0x1.2736f975d3b57p-55, 0x1.994129328c805p-56, -0x1.fffffffffffffp-110},
        {0x1.31677c77b4d02p-62, 0x1.a7615378454e9p-63, -0x1.fffffffffffffp-117},
        {-0x1.3db1f733be456p-87, -0x1.b86b45d2c7c74p-88, -0x1.65075b3baa854p-194},
        {0x1.453f5d718374ap-88, 0x1.c2e3888d4911bp-89, 0x1.fffffffffffffp-143},
        {0x1.47bc52cdc6bc1p-53, 0x1.c6568b98a9929p-54, 0x1.3977497829482p-159},
        {-0x1.4abb72eb058bep-91, -0x1.ca7e01c959788p-92, -0x1.9c974667cda43p-198},
        {0x1.51cc163375e5cp-100, 0x1.d4494fb79c5f9p-101, 0x1.235a318115a7dp-210},
        {0x1.530a89e8c2834p-79, 0x1.d602c792ff217p-80, 0x1.4d765bf788c32p-186},
        {-0x1.56fe8536a47e9p-91, -0x1.db7daf1e016dfp-92, -0x1.5a5357cd9fecap-199},
        {0x1.5f3addb5548c6p-60, 0x1.e6e878c6cb8f4p-61, 0x1.46dbd6dc7b9eep-168},
        {0x1.6102ff22f3431p-78, 0x1.e960cd938fc71p-79, 0x1.fffffffffffffp-133},
        {0x1.690ed9e3dd31p-55, 0x1.f4885e22dc71bp-56, -0x1.fffffffffffffp-110},
        {-0x1.6a480c34c7c5bp-70, -0x1.f63a8ce2364f3p-71, -0x1.11e154c338558p-177},
        {-0x1.712c6b2a267f5p-90, -0x1.ffc87ce076dfap-91, -0x1.922d1954bd733p-196},
        {0x1.7382bd647eca8p-59, 0x1.0182f7f3350e1p-59, 0x1.5902345c6d87ep-166},
        {0x1.760aba9c35ed1p-62, 0x1.03441ed22884fp-62, -0x1.fffffffffffffp-116},
        {-0x1.7e8ad7428117dp-105, -0x1.09287c79a1b1p-105, -0x1.0b8ae2384a213p-212},
        {-0x1.7e8ad7428117dp-106, -0x1.09287c79a1b1p-106, -0x1.0f17dd299eb52p-212},
        {-0x1.83266a65e67b3p-95, -0x1.0c5a1aeb10a7cp-95, -0x1.5d790953d37ccp-202},
        {0x1.8a5dd21ef35afp-104, 0x1.115aa0fb29a7p-104, -0x1.1p-157},
        {0x1.8b571f80771bep-90, 0x1.12076e976275dp-90, -0x1.fffffffffffffp-144},
        {-0x1.8bf6e9484dd46p-91, -0x1.127630515eb89p-91, -0x1.aa2e8ae4b621cp-198},
        {-0x1.986d43391ffdp-65, -0x1.1b19925f9fc06p-65, -0x1.1aada6205370bp-170},
        {0x1.99ec5e10fdc8bp-83, 0x1.1c231eacb2814p-83, 0x1.f82d478ebc7fap-192},
        {-0x1.9b219a1974289p-86, -0x1.1cf977003bdd6p-86, -0x1.2a8a589db0f16p-194},
        {-0x1.af82b29eef2ecp-74, -0x1.2b19ae19e4f3ep-74, -0x1.730d414c3032cp-180},
        {-0x1.b102d7663223fp-87, -0x1.2c23f2bc02277p-87, -0x1.1304b8a0f41cdp-194},
        {-0x1.c48ddf5beba98p-98, -0x1.39afc8fadbb98p-98, -0x1.37656827f3549p-203},
        {-0x1.cf23f6232620ep-94, -0x1.4106468e7b671p-94, -0x1.a1de1e34f2642p-200},
        {-0x1.e48acc7d41976p-97, -0x1.4fdbea8f31897p-97, -0x1.889c4c9736da4p-202},
        {0x1.f8d2954ab444fp-91, 0x1.5dea9642be3ccp-91, 0x1.109cd4f731735p-199},
        {-0x1.fe0e7458ac1fcp-105, -0x1.618b50a22cecp-105, -0x1.c261b621b891p-214},
        {-0x1.fe0e7458ac1fcp-106, -0x1.618b50a22cecp-106, -0x1.2c6cf6dc2bc4dp-212},
      };
      for (int i = 0; i < EXCEPTIONS; i++)
        if (x == exceptions[i][0])
          return exceptions[i][1] + exceptions[i][2];
#undef EXCEPTIONS
      /* the 2nd term of the Taylor expansion of 2^x-1 at x=0 is
         log(2)^2/2*x^2 */
      static const double C2 = 0x1.ebfbdff82c58fp-3; // log(2)^2/2
      a_mul (&h, &l, LN2H, x);
      l = __builtin_fma (LN2L, x, l);
      /* h+l approximates the first term x*log(2) */
      /* we add C2*x^2 last, so that in case there is a cancellation in
         LN2L*x+l, it will contribute more bits */
      l += C2 * x * x;
      return h + l;
    }
  }

  /* now -54 < x < -0x1.0527dbd87e24dp-51
     or 0x1.0527dbd87e24dp-51 < x < 1024 */

  double err, h, l;
  err = exp2m1_fast (&h, &l, x, ax <= 0x3fc0000000000000lu);
  if (x == TRACE) printf ("h=%la l=%la err=%la\n", h, l, err);
  double left = h + (l - err);
  double right = h + (l + err);
  if (left == right)
  {
    if (x == TRACE) printf ("fast path succeeded\n");
    return left;
  }

  if (x == TRACE) printf ("fast path failed\n");

  return exp2m1_accurate (x);
}

// fake function as long as GNU libc does not provide it
double exp2m1 (double x)
{
  return exp (x) - 1.0;
}
