/* Correctly-rounded atan2 function for two binary64 values.

Copyright (c) 2023 Paul Zimmermann

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#define TRACEY -0x0.0000000000001p-1022
#define TRACEX 0x1p+0

#include <stdio.h>
#include <stdint.h>
#include <assert.h>

// Warning: clang also defines __GNUC__
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#endif

#pragma STDC FENV_ACCESS ON

typedef union { double f; uint64_t u; } d64u64;

#include "tint.h"

// return non-zero if u (with sign bit cleared) encodes Inf or NaN
static inline int inf_or_nan (uint64_t u)
{
  return (u >> 52) == 0x7ff;
}

#define MASK 0x7ffffffffffffffful

static inline int is_nan (uint64_t u)
{
  u = u & MASK;
  uint64_t e = u >> 52;
  return e == 0x7ff && u != (e << 52);
}

static inline int is_inf (uint64_t u)
{
  return (u & MASK) == (0x7fful << 52);
}

// PI_H+PI_L approximates pi with error bounded by 2^-108.041
#define PI_H 0x1.921fb54442d18p+1
#define	PI_L 0x1.1a62633145c07p-53
// PI_OVER2_H+PI_OVER2_L approximates pi/2 with error bounded by 2^-109.041
#define PI_OVER2_H 0x1.921fb54442d18p+0
#define	PI_OVER2_L 0x1.1a62633145c07p-54
// PI_OVER4_H+PI_OVER4_L approximates pi/4 with error bounded by 2^-110.041
#define PI_OVER4_H 0x1.921fb54442d18p-1
#define	PI_OVER4_L 0x1.1a62633145c07p-55

/* The following polynomials z*P(z) and Q(z) are a rational approximation
   of atan(z) on [0,1] generated by the test_atan program from
   rminimax (revision 94902ef):
   The relative approximation error output by rminimax is:
   fpminimax error = 3.99613e-59 (this is the relative error for P(x)/Q(x)
   with respect to atan(x)/x, which equals the relative error for x*P(x)/Q(x)
   with respect to atan(x)).
   The content of the output file atan_fpminimax.sollya is the following
   (Numerator is P(x), and Denominator is Q(x)):
Numerator = [|
0x2.09c0fe2d4c44bb29c73989e7519ea91406726ca119adbfp-12,
0xb.3cf74b427d53e03ee590b839e751890f2570b12bcb2381ap-12,
0x2.c21262c5ee230e68478de0875e1363e89e56c52e12e75e3p-8,
0x7.ea5d53dda9586c1d92a12df585026e1c90046cfd9a5b47f8p-8,
0x1.2ca8329170bf670dc1702b59c84b50b37d942f8d3769ef4p-4,
0x2.5aaa9752ebff1643c8f6de0edb933954b15381534eda7df8p-4,
0x4.1e6a0dafd431588d6c7ceb71f5cec19a77a386c00fd01e5p-4,
0x6.5de3ba90cbe60835e3367d9f6f7d371ab4597cf27f5c488p-4,
0x8.cf8f7c585767042cd92a5b9ac13d8c8043bd4a023dbe04dp-4,
0xa.fdc36d6b36139bf11df63474e3859d442b30b2c089a2b6cp-4,
0xc.6f8fb14638225192f9f04cf55c103771c44675c6d483606p-4,
0xc.ce79f10f754e31591ce47edcbc8a4eeb2a6f721ac656b42p-4,
0xc.090384dbd77132e1dfb4d9a1d595de7e506ca899a394f7p-4,
0xa.556ac9eee25e867d84dafa25141d203f1c7c2a5156b3ec3p-4,
0x8.1bd2677ddfcbc381df33f27dbb60939cb4c2c73286a6c29p-4,
0x5.cf6890b4eb9746ce40ecaee7789e113cba5cabcb5c9e199p-4,
0x3.cb7db6a1d6d99beb0a774e9a709d31960ee49825db23c314p-4,
0x2.40b4d3536e443b61bcfb377f5abc2a7e3a5435f9c2a3a6c8p-4,
0x1.35df4832c39c240f59a062ecccea6ea27d5e854a7f98ca68p-4,
0x9.5db9977c5e6e26385367a63fab8a720fc2b63bd115998d8p-8,
0x4.0be5b6c11b6afa6b863c0af94484ecd862a74b8aae890acp-8,
0x1.8bdd8845186a4130f13cad7c3bdd36cf744b7b5025259982p-8,
0x8.40c38ccfcb5dc64b55a44095bf7f3126668b8792d4ecd08p-12,
0x2.5c1d2bdeca1ac67b082ab087cc4c3c74da7a7f6f75214a28p-12,
0x9.054011c32d4b7a5c68d3c5d525f4af4eeb3c98615dee188p-16,
0x1.bbb6945d5565762aea6ec351e1d3551a7e40c419a7c0eb76p-16,
0x4.077cd0d9f2cd5f28c7357f0328fefa4e8e0194f353816ce8p-20,
0x6.50b6ea4e69842a65d6c651bca00813e0fe3fa3cc2a4378bp-24,
0x5.05d00dc3a15d400f36e0a54a8b6bf820fa981ec3c482e978p-28,
-0x1.38088112d9cca2b819e68e1f4fe2158753b900d05822353ap-60|];
Denominator = [|
0x2.09c0fe2d4c44bb29c73989e7519ea91406726ca119adbfp-12,
0xb.3cf74b427d53e03ee590b839e751890f2570b12bcb238cfp-12,
0x2.ccf112bc350f27a3d109be11851c076e5e7927716e161108p-8,
0x8.264d256f0bf4d61ee21431cc0f29764ce0cc1b593ac9952p-8,
0x1.3b2f8928ed0f65ddde810f893bbca452e8578dc057f6dbfp-4,
0x2.83e22371eaae527bd88fc66b104f6c8e151d128593dc3b34p-4,
0x4.7ece38b955841470d4fb97d6d7e1efdd7cb50c07514b8bcp-4,
0x7.1c0b45bc528f70ab02523c0ae4048f5cfd5521189747598p-4,
0xa.164ccdbb65ee133e623433c5e086402cb228afd335a245fp-4,
0xc.ed0c0cbe44fac2fd7c2adfc7c5dda9ea22b4a311cf5a5b1p-4,
0xf.0e6660438c903713dca1a0f58f0d9438a92b9de68c4488cp-4,
0x1p+0,
0xf.8ea68f9ad849103b257e4bfc606967f818fa2816928c4aap-4,
0xd.dc64eeee350623447a33ea40a2b22e4a6a2c129ace2470ap-4,
0xb.52ddfba2d37c8e224551a9b19fa064a3d78c68b54bc385p-4,
0x8.7ac113d26b683a14e97756c38785b0bf75f0a4506931ba8p-4,
0x5.d0328385c8079eaf24ec7cf91c78f75b402ea46b3f8ee6c8p-4,
0x3.a40b4a92ff0891065173f9b20e96e0a1467aed15fe33328p-4,
0x2.1390172457ddda6c3eabcd30f14774e6a5fe82ba64e0b24cp-4,
0x1.12db48d8fcd9d767c15f816db67b77ea0c399fedcf1dffe8p-4,
0x8.01a0c1a0dfefc92f8e0a97902e08d4781898e0b7d8ef0bcp-8,
0x3.56742224c37c1f6ea32c00086127eebfe033246a82f77e24p-8,
0x1.3b6ad4d3096ee4639ef840e9c09012b2662dd954d548c09cp-8,
0x6.5ba286ceb1697344bc3da132cbbe8025d30ae77005420eb8p-12,
0x1.c254a5c056c9647d2f92273519dae2d8e142ed5a56be2da4p-12,
0x6.82bdb6848076986af025d8bf5c3cd2f11f689adb05f5038p-16,
0x1.363e39445fdef5ca334d0fe1480e7ddc0b5399791828af16p-16,
0x2.bae9c43c14eab0ecc3a975bec45bddd62a6f3fbd5a63e3c4p-20,
0x4.25cd6d03b66803e89f2a803039fbb58a67a12ccb411479fp-24,
0x3.3292e4119e1a4df48cf079a47049f07fd24f82de8f791668p-28|];
*/
static const tint_t P[30] = {
   {.h=0x82703f8b53112eca, .m=0x71ce6279d467aa45, .l=0x19c9b28466b6fc0, .ex=-10, .sgn=0},
   {.h=0xb3cf74b427d53e03, .m=0xee590b839e751890, .l=0xf2570b12bcb2381a, .ex=-8, .sgn=0},
   {.h=0xb08498b17b88c39a, .m=0x11e37821d784d8fa, .l=0x2795b14b84b9d78c, .ex=-6, .sgn=0},
   {.h=0xfd4baa7bb52b0d83, .m=0xb25425beb0a04dc3, .l=0x92008d9fb34b68ff, .ex=-5, .sgn=0},
   {.h=0x96541948b85fb386, .m=0xe0b815ace425a859, .l=0xbeca17c69bb4f7a0, .ex=-3, .sgn=0},
   {.h=0x96aaa5d4baffc590, .m=0xf23db783b6e4ce55, .l=0x2c54e054d3b69f7e, .ex=-2, .sgn=0},
   {.h=0x83cd41b5fa862b11, .m=0xad8f9d6e3eb9d833, .l=0x4ef470d801fa03ca, .ex=-1, .sgn=0},
   {.h=0xcbbc7752197cc106, .m=0xbc66cfb3edefa6e3, .l=0x568b2f9e4feb8910, .ex=-1, .sgn=0},
   {.h=0x8cf8f7c585767042, .m=0xcd92a5b9ac13d8c8, .l=0x43bd4a023dbe04d, .ex=0, .sgn=0},
   {.h=0xafdc36d6b36139bf, .m=0x11df63474e3859d4, .l=0x42b30b2c089a2b6c, .ex=0, .sgn=0},
   {.h=0xc6f8fb1463822519, .m=0x2f9f04cf55c10377, .l=0x1c44675c6d483606, .ex=0, .sgn=0},
   {.h=0xcce79f10f754e315, .m=0x91ce47edcbc8a4ee, .l=0xb2a6f721ac656b42, .ex=0, .sgn=0},
   {.h=0xc090384dbd77132e, .m=0x1dfb4d9a1d595de7, .l=0xe506ca899a394f70, .ex=0, .sgn=0},
   {.h=0xa556ac9eee25e867, .m=0xd84dafa25141d203, .l=0xf1c7c2a5156b3ec3, .ex=0, .sgn=0},
   {.h=0x81bd2677ddfcbc38, .m=0x1df33f27dbb60939, .l=0xcb4c2c73286a6c29, .ex=0, .sgn=0},
   {.h=0xb9ed12169d72e8d9, .m=0xc81d95dcef13c227, .l=0x974b95796b93c332, .ex=-1, .sgn=0},
   {.h=0xf2df6da875b666fa, .m=0xc29dd3a69c274c65, .l=0x83b9260976c8f0c5, .ex=-2, .sgn=0},
   {.h=0x902d34d4db910ed8, .m=0x6f3ecddfd6af0a9f, .l=0x8e950d7e70a8e9b2, .ex=-2, .sgn=0},
   {.h=0x9aefa41961ce1207, .m=0xacd0317666753751, .l=0x3eaf42a53fcc6534, .ex=-3, .sgn=0},
   {.h=0x95db9977c5e6e263, .m=0x85367a63fab8a720, .l=0xfc2b63bd115998d8, .ex=-4, .sgn=0},
   {.h=0x817cb6d8236d5f4d, .m=0x70c7815f28909d9b, .l=0xc54e97155d12158, .ex=-5, .sgn=0},
   {.h=0xc5eec4228c352098, .m=0x789e56be1dee9b67, .l=0xba25bda81292ccc1, .ex=-7, .sgn=0},
   {.h=0x840c38ccfcb5dc64, .m=0xb55a44095bf7f312, .l=0x6668b8792d4ecd08, .ex=-8, .sgn=0},
   {.h=0x97074af7b286b19e, .m=0xc20aac21f3130f1d, .l=0x369e9fdbdd48528a, .ex=-10, .sgn=0},
   {.h=0x9054011c32d4b7a5, .m=0xc68d3c5d525f4af4, .l=0xeeb3c98615dee188, .ex=-12, .sgn=0},
   {.h=0xdddb4a2eaab2bb15, .m=0x753761a8f0e9aa8d, .l=0x3f20620cd3e075bb, .ex=-15, .sgn=0},
   {.h=0x80ef9a1b3e59abe5, .m=0x18e6afe0651fdf49, .l=0xd1c0329e6a702d9d, .ex=-17, .sgn=0},
   {.h=0xca16dd49cd30854c, .m=0xbad8ca379401027c, .l=0x1fc7f47985486f16, .ex=-21, .sgn=0},
   {.h=0xa0ba01b8742ba801, .m=0xe6dc14a9516d7f04, .l=0x1f5303d878905d2f, .ex=-25, .sgn=0},
   {.h=0x9c0440896ce6515c, .m=0xcf3470fa7f10ac3, .l=0xa9dc80682c111a9d, .ex=-59, .sgn=1},
};

static const tint_t Q[30] = {
   {.h=0x82703f8b53112eca, .m=0x71ce6279d467aa45, .l=0x19c9b28466b6fc0, .ex=-10, .sgn=0},
   {.h=0xb3cf74b427d53e03, .m=0xee590b839e751890, .l=0xf2570b12bcb238cf, .ex=-8, .sgn=0},
   {.h=0xb33c44af0d43c9e8, .m=0xf4426f84614701db, .l=0x979e49dc5b858442, .ex=-6, .sgn=0},
   {.h=0x8264d256f0bf4d61, .m=0xee21431cc0f29764, .l=0xce0cc1b593ac9952, .ex=-4, .sgn=0},
   {.h=0x9d97c4947687b2ee, .m=0xef4087c49dde5229, .l=0x742bc6e02bfb6df8, .ex=-3, .sgn=0},
   {.h=0xa0f888dc7aab949e, .m=0xf623f19ac413db23, .l=0x854744a164f70ecd, .ex=-2, .sgn=0},
   {.h=0x8fd9c7172ab0828e, .m=0x1a9f72fadafc3dfb, .l=0xaf96a180ea297178, .ex=-1, .sgn=0},
   {.h=0xe38168b78a51ee15, .m=0x604a47815c8091eb, .l=0x9faaa42312e8eb30, .ex=-1, .sgn=0},
   {.h=0xa164ccdbb65ee133, .m=0xe623433c5e086402, .l=0xcb228afd335a245f, .ex=0, .sgn=0},
   {.h=0xced0c0cbe44fac2f, .m=0xd7c2adfc7c5dda9e, .l=0xa22b4a311cf5a5b1, .ex=0, .sgn=0},
   {.h=0xf0e6660438c90371, .m=0x3dca1a0f58f0d943, .l=0x8a92b9de68c4488c, .ex=0, .sgn=0},
   {.h=0x8000000000000000, .m=0x0, .l=0x0, .ex=1, .sgn=0},
   {.h=0xf8ea68f9ad849103, .m=0xb257e4bfc606967f, .l=0x818fa2816928c4aa, .ex=0, .sgn=0},
   {.h=0xddc64eeee3506234, .m=0x47a33ea40a2b22e4, .l=0xa6a2c129ace2470a, .ex=0, .sgn=0},
   {.h=0xb52ddfba2d37c8e2, .m=0x24551a9b19fa064a, .l=0x3d78c68b54bc3850, .ex=0, .sgn=0},
   {.h=0x87ac113d26b683a1, .m=0x4e97756c38785b0b, .l=0xf75f0a4506931ba8, .ex=0, .sgn=0},
   {.h=0xba065070b900f3d5, .m=0xe49d8f9f238f1eeb, .l=0x6805d48d67f1dcd9, .ex=-1, .sgn=0},
   {.h=0xe902d2a4bfc22441, .m=0x945cfe6c83a5b828, .l=0x519ebb457f8ccca0, .ex=-2, .sgn=0},
   {.h=0x84e405c915f7769b, .m=0xfaaf34c3c51dd39, .l=0xa97fa0ae99382c93, .ex=-2, .sgn=0},
   {.h=0x896da46c7e6cebb3, .m=0xe0afc0b6db3dbbf5, .l=0x61ccff6e78efff4, .ex=-3, .sgn=0},
   {.h=0x801a0c1a0dfefc92, .m=0xf8e0a97902e08d47, .l=0x81898e0b7d8ef0bc, .ex=-4, .sgn=0},
   {.h=0xd59d088930df07db, .m=0xa8cb00021849fbaf, .l=0xf80cc91aa0bddf89, .ex=-6, .sgn=0},
   {.h=0x9db56a6984b77231, .m=0xcf7c2074e0480959, .l=0x3316ecaa6aa4604e, .ex=-7, .sgn=0},
   {.h=0xcb7450d9d62d2e68, .m=0x9787b4265977d004, .l=0xba615cee00a841d7, .ex=-9, .sgn=0},
   {.h=0xe12a52e02b64b23e, .m=0x97c9139a8ced716c, .l=0x70a176ad2b5f16d2, .ex=-11, .sgn=0},
   {.h=0xd057b6d0900ed30d, .m=0x5e04bb17eb879a5e, .l=0x23ed135b60bea070, .ex=-13, .sgn=0},
   {.h=0x9b1f1ca22fef7ae5, .m=0x19a687f0a4073eee, .l=0x5a9ccbc8c14578b, .ex=-15, .sgn=0},
   {.h=0xaeba710f053aac3b, .m=0x30ea5d6fb116f775, .l=0x8a9bcfef5698f8f1, .ex=-18, .sgn=0},
   {.h=0x84b9ada076cd007d, .m=0x13e55006073f76b1, .l=0x4cf4259968228f3e, .ex=-21, .sgn=0},
   {.h=0xcca4b9046786937d, .m=0x233c1e691c127c1f, .l=0xf493e0b7a3de459a, .ex=-26, .sgn=0},
};

// use a type [29,29] rational approximation of atan(z) for 0 <= z <= 1
static double
atan2_accurate (double y, double x)
{
  /* first check when t=y/x is small and exact and x > 0, since for
     |t| <= 0x1.d12ed0af1a27fp-27, atan(t) rounds to t (to nearest) */
  double t = y / x;
  double corr = __builtin_fma (t, x, -y);
  if (corr == 0 && x > 0) // t is exact
    if (__builtin_fabs (t) <= 0x1.d12ed0af1a27fp-27)
      return __builtin_fma (t, -0x1p-54, t);

  int inv = __builtin_fabs (y) > __builtin_fabs (x);
  tint_t z[1], p[1], q[1];
  if (inv)
    div_tint_d (z, x, y);
  else
    div_tint_d (z, y, x);
  // below when we write y/x it should be read x/y when |x/y| < 1
  // |z - y/x| < 2^-185.53 * |z| (relative error from div_tint_d)
  // the rational approximation is only for z > 0, it is not antisymmetric
  int sz = z->sgn;
  z->sgn = 0;
  cp_tint (p, P + 29);
  cp_tint (q, Q + 29);
  for (int i = 28; i >= 0; i--)
  {
    mul_tint (p, p, z);
    mul_tint (q, q, z);
    add_tint (p, p, P + i);
    add_tint (q, q, Q + i);
  }
  // multiply p by z
  mul_tint (p, p, z);
  /* The routine errPsplit(e,13) in atan2.sage gives a relative error bound
     of 2^-184.14 for |p - z*P(z)|, for -11 <= e <= 0, which corresponds
     to 2^-12 <= z <= 1. */
  /* The routine errQsplit(e,12) in atan2.sage gives a relative error bound
     of 2^-184.19 for |q - Q(z)|, for -11 <= e <= 0, which corresponds
     to 2^-12 <= z <= 1. */
  // divide p by q
  div_tint (z, p, q);
  /* The relative error of div_tint() is <= 2^-185.53, thus we have:
     z*P(z)/Q(z) = atan(z) * (1 + eps0) with |eps0| < 3.99613e-59
     z = y/x * (1 + eps1) with |eps1| < 2^-185.53
     p = z*P(z) * (1 + eps2) with |eps2| < 2^-184.14
     q = Q(z) * (1 + eps3)   with |eps3| < 2^-184.19
     newz = p/q * (1 + eps4) with |eps4| < 2^-185.53
     The equality z = y/x * (1 + eps1) gives
     atan(z) = atan(y/x) + eps1*y/x * 1/(1+theta^2) for theta in (z,y/x).
     Thus |atan(z) - atan(y/x)| <= |eps1*y/x| which yields
     |atan(z) - atan(y/x)|/|atan(y/x)| <= |eps1*y/x|/|atan(y/x)|
     Since t/atan(t) is bounded by 1/atan(1) for 0 <= x <= 1, this yields:
     atan(z) = atan(y/x) * (1 + eps5) with |eps5| <= eps1/atan(1) < 2^-185.18.
     In summary we have:
     newz = atan(y/x)*(1+eps0)*(1+eps2)*(1+eps4)*(1+eps5)/(1+eps3)
     thus:
     newz = atan(y/x)*(1+eps6) with |eps6| < 2^-182.63.
     This corresponds to a maximal error of 2^-182.63*2^192 <= 662 ulps.
  */
  uint64_t err = 662; // error bound in case inv=0 and x > 0
  z->sgn = sz; // restore sign
  /* Now z approximates atan(y/x) for inv=0, and atan(x/y) for inv=1,
     with -pi/4 < z < pi/4.
  */
  if (inv)
  {
    // if x/y > 0 thus atan(x/y) > 0 we apply pi/2 - atan(x/y)
    // if x/y < 0 thus atan(x/y) < 0 we apply -pi/2 - atan(x/y)
    if (z->sgn == 0) { // 0 < atan(x/y) < pi/4
      z->sgn = 1;
      add_tint (z, &PI2, z);
      /* Now pi/4 < z < pi/2. The absolute error on z was bounded by
         2^-182.63*pi/4, the error on PI2 is bounded by 2^-197.96, and
         the add_tint() error is bounded by 2 ulp(pi/4) = 2^-191,
         which yields a total error < 2^-182.63*pi/4 + 2^-197.96 + 2^-191
         < 2^-182.97. Relatively to ulp(pi/4) this is less than 523. */
    }
    else // -pi/4 < atan(x/y) < 0
    {
      add_tint (z, &PI2, z);
      z->sgn = 1;
      /* Now -pi/2 < z < -pi/4. The same error analysis as above applies,
         thus we get the same bound of 523 ulps. */
    }
    err = 523;
  }
  // if x is negative we go to the opposite quadrant
  if (x < 0) {
    if (z->sgn == 0) { // 1st quadrant -> 3rd quadrant (subtract pi)
      z->sgn = 1;
      add_tint (z, &PI, z);
      z->sgn = 1;
      /* If inv=0 we had 0 < z < pi/4 thus now -pi < z < -3pi/4.
         If inv=1 we had pi/4 < z < pi/2 thus now -3pi/4 < z < -pi/2.
         In all cases the absolute error on z was bounded by 2^-182.97,
         that on PI is bounded by 2^-196.96, and the add_tint() error is
         bounded by 2 ulp(pi/2) = 2^-190, which yields a total error
         < 2^-182.97 + 2^-196.96 + 2^-190 < 2^-182.95.
         Relatively to ulp(pi/2) this is less than 266 ulps. */
    }
    else // 4th quadrant -> 2nd quadrant (add pi)
    {
      add_tint (z, &PI, z);
      /* If inv=0 we had -pi/4 < z < 0 thus now 3pi/4 < z < pi.
         If inv=1 we had -pi/2 < z < -pi/4 thus now pi/2 < z < 3pi/4.
         The same analysis as above applies, and we get the same bound
         of 266 ulps. */
    }
    err = 266;
  }
  return tint_tod (z, err, y, x);
}

/* The following are a degree-9 polynomial Pfast(x) and a degree-10 polynomial
   Qfast(x), both with double-double coefficient, such that Pfast(x)/Qfast(x)
   approximates atan(x)/x on [0,1] with relative precision 2.81818e-20, or
   x*Pfast(x)/Qfast(x) approximates atan(x) with the same relative precision.
   They were generated with revision 94902ef of rminimax, with the following
   changes in test_atan.cpp:
-  std::pair<size_t, size_t> type = std::make_pair(29u, 29u);
+  std::pair<size_t, size_t> type = std::make_pair(9u, 10u);
-  mp_prec_t man_size = 192ul;
+  mp_prec_t man_size = 106ul;
*/
static double Pfast[20] = {
  0x1.572d2a15a7e42p-3, 0x1.d873377734d58p-58, // degree 0
  0x1.5d6e7a0f6fd67p-2, -0x1.704d6ea0dbf8p-61,
  0x1.531337591c0fdp-1, 0x1.7245c7c222e5cp-56,
  0x1.96b85a3497371p-1, 0x1.237f25f712358p-56,
  0x1.9699e31ba635bp-1, 0x1.beaef043d3ad8p-55,
  0x1.2f389f46bce11p-1, 0x1.59b7e80c80c6p-56,
  0x1.6268ecc20f6fdp-2, 0x1.9f1a295aad66p-59,
  0x1.2e2e6fa0928fdp-3, -0x1.3f26aa9ad42d8p-57,
  0x1.5b377b5683dadp-5, 0x1.45f16809d73ep-60,
  0x1.9b473aa37aa8ep-8, 0x1.b43f7d9b5f5b8p-63, // degree 9
};

static double Qfast[22] = {
  0x1.572d2a15a7e42p-3, 0x1.d8cc5be26128p-58,   // degree 0
  0x1.5d6e7a0f6fd67p-2, -0x1.9938bce38319p-58,
  0x1.6fac50303f635p-1, -0x1.ddcd4c98e34p-63,
  0x1.d0f56e8c7f0fcp-1, 0x1.0c30c8db073p-60,
  0x1p+0, 0x0p+0,
  0x1.a743a6da0ac6ep-1, 0x1.31307707bdda8p-56,
  0x1.1e97e129470a3p-1, -0x1.d27de55d97a4p-56,
  0x1.2933c1772591ep-2, 0x1.a64f10a00089p-58,
  0x1.ce97fd0d9ddc2p-4, 0x1.9121fac6e9aaep-58,
  0x1.e350ea6bc42eep-6, 0x1.c0dd3c31989bcp-61,  // degree 9
  0x1.05f0a6795af03p-8, -0x1.9d3d53dc179d4p-62, // degree 10
};

/* h + l <- bh / ah with relative error bounded by 2^-98.41
   (copied and simplified from tan.c) */
static void fast_div1 (double *h, double *l, double bh, double ah)
{
  /* We use here Karp-Markstein's trick for division:
     let b = bh, a = ah, y = o(1/a), and z = o(b*y),
     then the approximation of b/a is z' = z + y*(b-a*z):
     b-a*z' = b-a*(z + y*(b-a*z)) = (b-a*z)*(1-a*y).
     We distinguish two errors:
     * the mathematical error, assuming z + y*(b-a*z) is computed exactly
       (but taking into account that y is not exactly 1/a, and z is not
       exactly b/a
     * the rounding errors in z + y*(b-a*z)
     For the error analysis, we assume 1 <= ah, bh < 2.
  */
  double y = 1.0 / ah;
  /* y = 1/ah / (1 + eps1) with |eps1| < 2^-52.
     |1-ah*y| < |eps1| < 2^-52. */
  *h = bh * y;
  /* h = bh * y / (1 + eps2) with |eps2| < 2^-52
       = bh/ah / (1 + eps1) / (1 + eps2)
     thus writing z = h:
     bh = ah*z * (1 + eps1) * (1 + eps2)
     |bh - ah*z| < ah*z * (eps1 + eps2 + eps1*eps2)
     Since ah < 2 and z <= bh*y < 2, we have:
     |bh - ah*z| < 4 * (2*2^-52 + 2^-104) < 2^-48.999.
     It follows |bh-ah*z'| < (bh-ah*z)*(1-ah*y) < 2^-48.999*2^-52 < 2^-100.999
     Dividing by ah>=1 yields: |bh/ah-z'| < 2^-100.999 too.
     We assume the same bound hold for b,a: |b/a-z'| < 2^-100.999.
  */
  double eh = __builtin_fma (ah, -*h, bh);
  /* from the analysis above, we have |eh| < 2^-48.999 thus the rounding error
     is bounded by ulp(2^-48.999) = 2^-101 */
  *l = y * eh;
  /* We have y < 1 and |eh| < 2^-48.999, thus |l| < 2^-48.999 and the rounding
     error on l is bounded by ulp(2^-48.999) = 2^-101.
     The total rounding error is thus bounded by:
     2^-101+2^-101 < 2^-100.
     Adding the mathematical error yields:
     2^-100.999 + 2^-100 < 2^-99.41.
     | h + l - (bh + bl) / (ah + al) | < 2^-99.41.

     This was assuming 1 <= a,b < 2, thus with 1/2 <= h+l <= 2.
     For the relative error, this corresponds to 2^-99.41/(1/2) = 2^-98.41
     where 1/2 is the smallest possible value of h+l. */
}

// h + l <- (bh + bl) / (ah + al) (copied from tan.c)
static inline void
fast_div (double *h, double *l, double bh, double bl, double ah, double al)
{
  double y = 1.0 / ah;
  *h = bh * y;
  double eh = __builtin_fma (ah, -*h, bh);
  double el = __builtin_fma (al, -*h, bl);
  *l = y * (eh + el);
}

static inline void
fast_two_sum (double *hi, double *lo, double a, double b)
{
  double e;

  *hi = a + b;
  e = *hi - a; /* exact */
  *lo = b - e; /* exact */
}

// assumes |ah| >= |bh|
static inline void
dd_sum_fast (double *h, double *l, double ah, double al, double bh, double bl)
{
  fast_two_sum (h, l, ah, bh);
  *l += al + bl;
}

static inline void
dd_sum (double *h, double *l, double ah, double al, double bh, double bl)
{
  if (__builtin_fabs (ah) >= __builtin_fabs (bh))
    fast_two_sum (h, l, ah, bh);
  else
    fast_two_sum (h, l, bh, ah);
  *l += al + bl;
}

// Multiply exactly a and b, such that *hi + *lo = a * b. 
static inline void a_mul(double *hi, double *lo, double a, double b) {
  *hi = a * b;
  *lo = __builtin_fma (a, b, -*hi);
}

// Returns (ah + al) * (bh + bl) - (al * bl)
// We can ignore al * bl when assuming al <= ulp(ah) and bl <= ulp(bh)
static inline void d_mul(double *hi, double *lo, double ah, double al,
                         double bh, double bl) {
  double s, t;

  a_mul(hi, &s, ah, bh);
  t = __builtin_fma(al, bh, s);
  *lo = __builtin_fma(ah, bl, t);
}

#define PIH 0x1.921fb54442d18p+1
#define PIL 0x1.1a62633145c07p-53
#define PIOVER2H 0x1.921fb54442d18p+0
#define PIOVER2L 0x1.1a62633145c07p-54

// fast path: return err such that |h + l - atan2(y,x)| < err*h 
static double atan2_fast (double *h, double *l, double y, double x)
{
  // int bug = y == TRACEY && x == TRACEX;
  d64u64 vy = {.f = y}, vx = {.f = x};
  uint64_t ay = vy.u << 1, ax = vx.u << 1;
  int inv = ay > ax, negx = vx.u >> 63, negz = (vy.u ^ vx.u) >> 63;
  // if (bug) printf ("inv=%d negx=%d negz=%d\n", inv, negx, negz);
  if (inv) { double t = y; y = x; x = t; }
  // now |y| <= |x|
  double zh, zl;
  // if (bug) printf ("y=%la x=%la\n", y, x);
  fast_div1 (&zh, &zl, y, x);
  //if (bug) printf ("zh=%la zl=%la\n", zh, zl);

  // zh + zl = y/x * (1 + eps1) with |eps1| < 2^-98.41
  // the rational approximation is only for z > 0, it is not antisymmetric
  double sz = 1.0;
  if (zh < 0) { zh = -zh; zl = -zl; sz = -1.0; }
  double qh = Qfast[20], ql = Qfast[21]; // Q[10]
  // multiply by z
  d_mul (&qh, &ql, zh, zl, qh, ql);
  // add Q[9]
  dd_sum_fast (&qh, &ql, Qfast[18], Qfast[19], qh, ql);
  double ph = Pfast[18], pl = Pfast[19]; // P[9]
  /* FIXME: since |z| <= 1, the value of ph+pl at the beginning of step i is
     bounded by |P[i+1|+|P[i+2]|+...+|P[9]|. This is smaller than |P[i]|
     for i >= 5, thus we can use dd_sum_fast(). Same for Q[i] for i >= 6. */
  for (int i = 8; i >= 6; i--)
  {
    // multiply by z
    d_mul (&ph, &pl, zh, zl, ph, pl);
    d_mul (&qh, &ql, zh, zl, qh, ql);
    dd_sum_fast (&ph, &pl, Pfast[2*i], Pfast[2*i+1], ph, pl); // add P[i]
    dd_sum_fast (&qh, &ql, Qfast[2*i], Qfast[2*i+1], qh, ql); // add Q[i]
  }
  // i=5
  d_mul (&ph, &pl, zh, zl, ph, pl);
  d_mul (&qh, &ql, zh, zl, qh, ql);
  dd_sum_fast (&ph, &pl, Pfast[10], Pfast[11], ph, pl); // add P[i]
  dd_sum (&qh, &ql, Qfast[10], Qfast[11], qh, ql); // add Q[i]
  for (int i = 4; i >= 0; i--)
  {
    // multiply by z
    d_mul (&ph, &pl, zh, zl, ph, pl);
    d_mul (&qh, &ql, zh, zl, qh, ql);
    dd_sum (&ph, &pl, Pfast[2*i], Pfast[2*i+1], ph, pl); // add P[i]
    dd_sum (&qh, &ql, Qfast[2*i], Qfast[2*i+1], qh, ql); // add Q[i]
  }
  // multiply ph+pl by z
  d_mul (&ph, &pl, zh, zl, ph, pl);
  // divide ph+pl by qh+ql
  fast_div (h, l, ph, pl, qh, ql);
  // restore sign
  *h *= sz;
  *l *= sz;
  //if (bug) printf ("h=%la l=%la\n", *h, *l);
  if (inv)
  {
    if (!negz)
      // if y/x > 0 thus atan(y/x) > 0 we apply pi/2 - atan(y/x)
      dd_sum (h, l, PIOVER2H, PIOVER2L, -*h, -*l);
    else
      // if y/x < 0 thus atan(y/x) < 0 we apply -pi/2 - atan(y/x)
      dd_sum (h, l, -PIOVER2H, -PIOVER2L, -*h, -*l);
  }
  //if (bug) printf ("h=%la l=%la x=%la\n", *h, *l, x);
  if (negx)
  {
    if (!negz)
      // 1st quadrant -> 3rd quadrant (subtract pi)
      dd_sum (h, l, -PIH, -PIL, *h, *l);
    else
      // 4th quadrant -> 2nd quadrant (add pi)
      dd_sum (h, l, PIH, PIL, *h, *l);
  }
  //if (bug) printf ("h=%la l=%la\n", *h, *l);
  return 0x1.0bp-65; // 2.81818e-20 < 0x1.0bp-65
}

// atan(y/x)
double cr_atan2 (double y, double x)
{
  d64u64 uy = {.f = y}, ux = {.f = x};
  uint64_t ay = uy.u & MASK, ax = ux.u & MASK;

  if (__builtin_expect (inf_or_nan (ay) || inf_or_nan (ax), 0))
  {
    if (is_nan (ay) || is_nan (ax))
      return y + x; // if y or x is sNaN, returns qNaN are raises invalid
    // Now neither y nor x is NaN, but at least one is +Inf or -Inf
    if (is_inf (ay) && is_inf (ax)) // both y and x are +/-Inf
    {
      // atan2 (+/-Inf,-Inf) = +/-3pi/4
      if (x < 0)
        return (y > 0) ? 3 * PI_OVER4_H + 3 * PI_OVER4_L
          : -3 * PI_OVER4_H - 3 * PI_OVER4_L;
      // atan2 (+/-Inf,+Inf) = +/-pi/4
      return (y > 0) ? PI_OVER4_H + PI_OVER4_L : -PI_OVER4_H - PI_OVER4_L;
    }
    // now only one of y and x is +/-Inf
    if (is_inf (ax))
    {
      if (x < 0)
        return (uy.u >> 63) ? -PI_H - PI_L : PI_H + PI_L;
      // atan2(+/-0,x) = +/-0 for x > 0
      // atan2(+/-y,+Inf) = +/-0 for finite y>0
      return __builtin_copysign (0, y);
    }
    // now y = +/-Inf
    // atan2(+/-Inf,x) = +/-pi/2 for finite x
    return (y > 0) ? PI_OVER2_H + PI_OVER2_L : -PI_OVER2_H - PI_OVER2_L;
  }

  if (__builtin_expect (y == 0 || x == 0, 0))
  {
    if (y == 0 && x == 0)
    {
      if (ux.u == 0) // atan2(+/-0, +0) = +/-0
        return y;
      // atan2(+/-0, +0) = +/-pi
      return (uy.u == 0) ? PI_H + PI_L : -PI_H - PI_L;
    }
    // only one of y and x is zero
    if (y == 0)
    {
      // atan2(+/-0,x) = +/-0 for x>0
      if (x > 0) return y;
      // atan2(+/-0,x) = +/-pi for x<0
      return (uy.u == 0) ? PI_H + PI_L : -PI_H - PI_L;
    }
    // now only x is zero
    // atan2(y,+/-0) = -pi/2 for y<0
    // atan2(y,+/-0) = +pi/2 for y>0
    return (y > 0) ? PI_OVER2_H + PI_OVER2_L : -PI_OVER2_H - PI_OVER2_L;
  }

  // now both y and x are neither NaN, nor +/-Inf, nor +/-0

  /* check when y/x is small and exact and x > 0, since for
     |t| <= 0x1.d12ed0af1a27fp-27, atan(t) rounds to t (to nearest) */
  double t = y / x;
  double corr = __builtin_fma (t, x, -y);
  if (__builtin_expect (corr == 0 && x > 0, 0)) // t is exact
    if (__builtin_fabs (t) <= 0x1.d12ed0af1a27fp-27)
      return __builtin_fma (t, -0x1p-54, t);

  double h, l, err;
  err = atan2_fast (&h, &l, y, x);
  double left =  h + __builtin_fma (h, -err, l);
  double right = h + __builtin_fma (h, +err, l);
  if (left == right)
    return left;

  return atan2_accurate (y, x);
}
